	.align 2
voicegroup606::
	voice_keysplit voicegroup233, KeySplitTable35                                                       @ 000 | HGSS Piano
	voice_keysplit voicegroup257, KeySplitTable47                                                       @ 001 | HGSS Cello
	voice_keysplit voicegroup269, KeySplitTable55                                                       @ 002 | HGSS Orchestral Hit
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_celesta, 255, 0, 255, 165                 @ 003 | GS2 Celesta
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 004 | ---
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 188, 103, 165    @ 005 | RSE Electric Piano
	voice_keysplit voicegroup234, KeySplitTable36                                                       @ 006 | HGSS Piano 2
	voice_keysplit voicegroup250, KeySplitTable32                                                       @ 007 | HGSS Dist. Guitar 2
	voice_keysplit voicegroup238, KeySplitTable36                                                       @ 008 | HGSS Vibraphone
	voice_keysplit voicegroup243, KeySplitTable38                                                       @ 009 | HGSS Music Box
	voice_keysplit voicegroup243, KeySplitTable38                                                       @ 010 | HGSS Music Box
	voice_keysplit voicegroup243, KeySplitTable38                                                       @ 011 | HGSS Music Box
	voice_keysplit voicegroup238, KeySplitTable36                                                       @ 012 | HGSS Vibraphone
	voice_keysplit voicegroup240, KeySplitTable39                                                       @ 013 | HGSS Xylophone
	voice_keysplit voicegroup239, KeySplitTable38                                                       @ 014 | HGSS Marimba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 015 | ---
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188           @ 016 | RSE Church Organ 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 017 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 018 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 019 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 020 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 021 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 022 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 023 | ---
	voice_keysplit voicegroup247, KeySplitTable41                                                       @ 024 | HGSS Nylon Guitar
	voice_keysplit voicegroup248, KeySplitTable41                                                       @ 025 | HGSS Martin Guitar
	voice_keysplit voicegroup251, KeySplitTable41                                                       @ 026 | HGSS Clean Guitar
	voice_keysplit voicegroup251, KeySplitTable41                                                       @ 027 | HGSS Clean Guitar
	voice_keysplit voicegroup251, KeySplitTable41                                                       @ 028 | HGSS Clean Guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127      @ 029 | RSE OD Guitar
	voice_keysplit voicegroup249, KeySplitTable32                                                       @ 030 | HGSS Dist. Guitar 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 031 | ---
	voice_keysplit voicegroup252, KeySplitTable42                                                       @ 032 | HGSS Upright Bass
	voice_keysplit voicegroup253, KeySplitTable43                                                       @ 033 | HGSS Fingered Bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 198                @ 034 | RSE Fretless Bass 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 035 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 036 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 192                    @ 037 | HGSS Slap Bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 146                   @ 038 | RSE Synth Bass
	voice_keysplit voicegroup254, KeySplitTable44                                                       @ 039 | HGSS Synth Bass
	voice_keysplit voicegroup256, KeySplitTable46                                                       @ 040 | HGSS Violin
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 041 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 042 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 043 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 044 | ---
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165            @ 045 | RSE Pizzacito
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 51, 242                        @ 046 | RSE Harp
	voice_keysplit voicegroup260, KeySplitTable40                                                       @ 047 | HGSS Timpani
	voice_keysplit voicegroup255, KeySplitTable45                                                       @ 048 | HGSS Strings
	voice_keysplit voicegroup006, KeySplitTableGBAStringEnsembleCustom                                  @ 049 | RSE Strings
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_choir, 255, 0, 255, 165                   @ 050 | GS2 Strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 051 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 197, 255, 171                    @ 052 | HGSS Tenor Choir
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 053 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 054 | ---
	voice_keysplit voicegroup269, KeySplitTable55                                                       @ 055 | HGSS Orchestral Hit
	voice_keysplit voicegroup007, KeySplitTableGBATrumpetCustom                                         @ 056 | RSE Trumpet
	voice_keysplit voicegroup261, KeySplitTable39                                                       @ 057 | HGSS Trumpet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 058 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 059 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 060 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_brass, 255, 0, 255, 165                   @ 061 | GS2 Brass Section
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 062 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 063 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192                   @ 064 | HGSS Alto Sax
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192                   @ 065 | HGSS Alto Sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 066 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 067 | ---
	voice_keysplit voicegroup265, KeySplitTable51                                                       @ 068 | HGSS Oboe
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 069 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 070 | ---
	voice_keysplit voicegroup266, KeySplitTable52                                                       @ 071 | HGSS Clarinet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 072 | ---
	voice_keysplit voicegroup267, KeySplitTable53                                                       @ 073 | HGSS Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 074 | ---
	voice_directsound 60, 0, DirectSoundWaveData_golden_sun_2_pan_flute, 255, 0, 255, 165               @ 075 | GS2 Pan Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 076 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 077 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 078 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 246, 78, 192                    @ 079 | HGSS Whistle
	voice_square_2_alt 60, 0, 3, 0, 1, 7, 0                                                             @ 080 | Sq-2
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171                  @ 081 | HGSS Sawtooth
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 082 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 083 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 084 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 085 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 086 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 087 | ---
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_choir_ohhs, 255, 188, 220, 243                  @ 088 | RF Voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 089 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 090 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 091 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 092 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 093 | ---
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_choir_ohhs, 255, 188, 220, 243                  @ 094 | RF Voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 095 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 096 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 097 | ---
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_music_box, 255, 0, 255, 235                     @ 098 | RF Music Box
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_music_box, 255, 0, 255, 235                     @ 099 | RF Music Box
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 100 | ---
	voice_directsound 60, 0, DirectSoundWaveData_thpprf_choir_ohhs, 255, 188, 220, 243                  @ 101 | RF Voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 102 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 103 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 104 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 105 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 106 | ---
	voice_keysplit voicegroup271, KeySplitTable56                                                       @ 107 | HGSS Koto
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 108 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 109 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 110 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 111 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 112 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 113 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 114 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 115 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 116 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 117 | ---
	voice_directsound 60, 0, DirectSoundWaveData_hg_138tom, 255, 0, 255, 171                            @ 118 | HGSS Tom
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 119 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 120 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 121 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 122 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 123 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                             @ 124 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_spearpillarwind60, 255, 0, 255, 32                  @ 125 | HGSS Wind
	voice_directsound 60, 0, DirectSoundWaveData_hg_062chh, 255, 242, 0, 171                            @ 126 | HGSS Open Hit Hat
	voice_keysplit_all voicegroup230                                                                    @ 127 | HGSS Drum
