#ifndef GUARD_CONSTANTS_MOVES_H
#define GUARD_CONSTANTS_MOVES_H

#define MOVE_NONE 0
#define MOVE_POUND 1
#define MOVE_KARATE_CHOP 2
#define MOVE_DOUBLE_SLAP 3
#define MOVE_DOUBLESLAP MOVE_DOUBLE_SLAP // Pre-Gen VI name
#define MOVE_COMET_PUNCH 4
#define MOVE_MEGA_PUNCH 5
#define MOVE_NEW_MEGATON_PUNCH MOVE_MEGA_PUNCH // TNDYS
#define MOVE_PAY_DAY 6
#define MOVE_FIRE_PUNCH 7
#define MOVE_ICE_PUNCH 8
#define MOVE_THUNDER_PUNCH 9
#define MOVE_THUNDERPUNCH MOVE_THUNDER_PUNCH // Pre-Gen VI name
#define MOVE_SCRATCH 10
#define MOVE_VISE_GRIP 11
#define MOVE_VICEGRIP MOVE_VISE_GRIP // Pre-Gen VI name
#define MOVE_VICE_GRIP MOVE_VISE_GRIP // Pre-Gen VIII name
#define MOVE_GUILLOTINE 12
#define MOVE_NEW_DIVINE_WRATH MOVE_GUILLOTINE // TNDYS
#define MOVE_RAZOR_WIND 13
#define MOVE_NEW_GUST MOVE_RAZOR_WIND // TNDYS
#define MOVE_SWORDS_DANCE 14
#define MOVE_CUT 15
#define MOVE_GUST 16
#define MOVE_NEW_RAZOR_WIND MOVE_GUST // TNDYS
#define MOVE_WING_ATTACK 17
#define MOVE_NEW_GALE MOVE_WING_ATTACK // TNDYS
#define MOVE_WHIRLWIND 18
#define MOVE_FLY 19
#define MOVE_BIND 20
#define MOVE_SLAM 21
#define MOVE_VINE_WHIP 22
#define MOVE_STOMP 23
#define MOVE_DOUBLE_KICK 24
#define MOVE_MEGA_KICK 25
#define MOVE_JUMP_KICK 26
#define MOVE_ROLLING_KICK 27
#define MOVE_SAND_ATTACK 28
#define MOVE_HEADBUTT 29
#define MOVE_HORN_ATTACK 30
#define MOVE_NEW_KNIFE_THROW MOVE_HORN_ATTACK // TNDYS
#define MOVE_FURY_ATTACK 31
#define MOVE_NEW_MAGICAL_KNIFE MOVE_FURY_ATTACK // TNDYS
#define MOVE_HORN_DRILL 32
#define MOVE_NEW_SOUL_SCULPTURE MOVE_HORN_DRILL // TNDYS
#define MOVE_TACKLE 33
#define MOVE_BODY_SLAM 34
#define MOVE_WRAP 35
#define MOVE_TAKE_DOWN 36
#define MOVE_NEW_DARK_IMPACT MOVE_TAKE_DOWN // TNDYS
#define MOVE_THRASH 37
#define MOVE_DOUBLE_EDGE 38
#define MOVE_TAIL_WHIP 39
#define MOVE_POISON_STING 40
#define MOVE_TWINEEDLE 41
#define MOVE_NEW_SEALING_NEEDLE MOVE_TWINEEDLE // TNDYS
#define MOVE_PIN_MISSILE 42
#define MOVE_LEER 43
#define MOVE_BITE 44
#define MOVE_GROWL 45
#define MOVE_ROAR 46
#define MOVE_SING 47
#define MOVE_SUPERSONIC 48
#define MOVE_NEW_JAMMING MOVE_SUPERSONIC // TNDYS
#define MOVE_SONIC_BOOM 49
#define MOVE_SONICBOOM MOVE_SONIC_BOOM // Pre-Gen VI name
#define MOVE_DISABLE 50
#define MOVE_ACID 51
#define MOVE_EMBER 52
#define MOVE_FLAMETHROWER 53
#define MOVE_MIST 54
#define MOVE_NEW_WHITE_MIST MOVE_MIST // TNDYS
#define MOVE_WATER_GUN 55
#define MOVE_HYDRO_PUMP 56
#define MOVE_SURF 57
#define MOVE_ICE_BEAM 58
#define MOVE_NEW_ICE_LASER 5MOVE_ICE_BEAM // TNDYS
#define MOVE_BLIZZARD 59
#define MOVE_PSYBEAM 60
#define MOVE_BUBBLE_BEAM 61
#define MOVE_BUBBLEBEAM MOVE_BUBBLE_BEAM // Pre-Gen VI name
#define MOVE_AURORA_BEAM 62
#define MOVE_HYPER_BEAM 63
#define MOVE_NEW_DESTRUCTION_BEAM MOVE_HYPER_BEAM // TNDYS
#define MOVE_PECK 64
#define MOVE_DRILL_PECK 65
#define MOVE_NEW_WING_SCREW MOVE_DRILL_PECK // TNDYS
#define MOVE_SUBMISSION 66
#define MOVE_LOW_KICK 67
#define MOVE_COUNTER 68
#define MOVE_SEISMIC_TOSS 69
#define MOVE_STRENGTH 70
#define MOVE_ABSORB 71
#define MOVE_MEGA_DRAIN 72
#define MOVE_LEECH_SEED 73
#define MOVE_NEW_MISTLETOE_SEED MOVE_LEECH_SEED // TNDYS
#define MOVE_GROWTH 74
#define MOVE_RAZOR_LEAF 75
#define MOVE_SOLAR_BEAM 76
#define MOVE_SOLARBEAM MOVE_SOLAR_BEAM // Pre-Gen VI name
#define MOVE_POISON_POWDER 77
#define MOVE_POISONPOWDER MOVE_POISON_POWDER // Pre-Gen VI name
#define MOVE_STUN_SPORE 78
#define MOVE_STUN_POWDER MOVE_STUN_SPORE // TNDYS
#define MOVE_SLEEP_POWDER 79
#define MOVE_PETAL_DANCE 80
#define MOVE_NEW_BATTLE_CHANT MOVE_PETAL_DANCE // TNDYS
#define MOVE_STRING_SHOT 81
#define MOVE_NEW_WIRE_WEB MOVE_STRING_SHOT // TNDYS
#define MOVE_DRAGON_RAGE 82
#define MOVE_NEW_SURGE_FIST MOVE_DRAGON_RAGE // TNDYS
#define MOVE_FIRE_SPIN 83
#define MOVE_THUNDER_SHOCK 84
#define MOVE_THUNDERSHOCK MOVE_THUNDER_SHOCK // Pre-Gen VI name
#define MOVE_THUNDERBOLT 85
#define MOVE_THUNDER_WAVE 86
#define MOVE_THUNDER 87
#define MOVE_ROCK_THROW 88
#define MOVE_NEW_ROCK_SLIDE MOVE_ROCK_THROW // TNDYS
#define MOVE_EARTHQUAKE 89
#define MOVE_FISSURE 90
#define MOVE_DIG 91
#define MOVE_TOXIC 92
#define MOVE_CONFUSION 93
#define MOVE_NEW_PSYSHOT MOVE_CONFUSION // TNDYS
#define MOVE_PSYCHIC 94
#define MOVE_NEW_MANA_BURST MOVE_PSYCHIC // TNDYS
#define MOVE_HYPNOSIS 95
#define MOVE_MEDITATE 96
#define MOVE_AGILITY 97
#define MOVE_QUICK_ATTACK 98
#define MOVE_RAGE 99
#define MOVE_TELEPORT 100
#define MOVE_NIGHT_SHADE 101
#define MOVE_MIMIC 102
#define MOVE_SCREECH 103
#define MOVE_DOUBLE_TEAM 104
#define MOVE_NEW_ILLUSION_STEP MOVE_DOUBLE_TEAM // TNDYS
#define MOVE_RECOVER 105
#define MOVE_HARDEN 106
#define MOVE_MINIMIZE 107
#define MOVE_SMOKESCREEN 108
#define MOVE_CONFUSE_RAY 109
#define MOVE_WITHDRAW 110
#define MOVE_DEFENSE_CURL 111
#define MOVE_BARRIER 112
#define MOVE_LIGHT_SCREEN 113
#define MOVE_HAZE 114
#define MOVE_NEW_BLACK_MIST MOVE_HAZE // TNDYS
#define MOVE_REFLECT 115
#define MOVE_FOCUS_ENERGY 116
#define MOVE_BIDE 117
#define MOVE_NEW_COVER_MOVE MOVE_BIDE // TNDYS
#define MOVE_METRONOME 118
#define MOVE_MIRROR_MOVE 119
#define MOVE_NEW_FALSE_SWIPE MOVE_MIRROR_MOVE // TNDYS
#define MOVE_SELF_DESTRUCT 120
#define MOVE_SELFDESTRUCT MOVE_SELF_DESTRUCT // Pre-Gen VI name
#define MOVE_EGG_BOMB 121
#define MOVE_NEW_MIND_BOMB MOVE_EGG_BOMB // TNDYS
#define MOVE_LICK 122
#define MOVE_SMOG 123
#define MOVE_NEW_MIASMA_GAS MOVE_SMOG // TNDYS
#define MOVE_SLUDGE 124
#define MOVE_NEW_POISON_BOMB MOVE_SLUDGE // TNDYS
#define MOVE_BONE_CLUB 125
#define MOVE_NEW_DOUBLE_DAGGER MOVE_BONE_CLUB // TNDYS
#define MOVE_FIRE_BLAST 126
#define MOVE_WATERFALL 127
#define MOVE_NEW_WATERFALL_CLIMB MOVE_WATERFALL // TNDYS
#define MOVE_CLAMP 128
#define MOVE_NEW_MANA_SHIELD MOVE_CLAMP // TNDYS
#define MOVE_SWIFT 129
#define MOVE_NEW_SPEED_STAR MOVE_SWIFT // TNDYS
#define MOVE_SKULL_BASH 130
#define MOVE_SPIKE_CANNON 131
#define MOVE_NEW_NEEDLE_SQUALL MOVE_SPIKE_CANNON // TNDYS
#define MOVE_CONSTRICT 132
#define MOVE_AMNESIA 133
#define MOVE_NEW_MEMORY_LAPSE MOVE_AMNESIA // TNDYS
#define MOVE_KINESIS 134
#define MOVE_NEW_TIME_FREEZE MOVE_KINESIS // TNDYS
#define MOVE_SOFT_BOILED 135
#define MOVE_SOFTBOILED MOVE_SOFT_BOILED // Pre-Gen VI name
#define MOVE_HIGH_JUMP_KICK 136
#define MOVE_HI_JUMP_KICK MOVE_HIGH_JUMP_KICK // Pre-Gen VI name
#define MOVE_GLARE 137
#define MOVE_NEW_COERCE MOVE_GLARE // TNDYS
#define MOVE_DREAM_EATER 138
#define MOVE_POISON_GAS 139
#define MOVE_NEW_MISTFALL_GAS MOVE_POISON_GAS // TNDYS
#define MOVE_BARRAGE 140
#define MOVE_NEW_BALL_BARRAGE MOVE_BARRAGE // TNDYS
#define MOVE_LEECH_LIFE 141
#define MOVE_NEW_BLOOD_SUCKER MOVE_LEECH_LIFE // TNDYS
#define MOVE_LOVELY_KISS 142
#define MOVE_NEW_DEMONS_KISS MOVE_LOVELY_KISS // TNDYS
#define MOVE_SKY_ATTACK 143
#define MOVE_TRANSFORM 144
#define MOVE_BUBBLE 145
#define MOVE_DIZZY_PUNCH 146
#define MOVE_SPORE 147
#define MOVE_NEW_BURN_POWDER MOVE_SPORE // TNDYS
#define MOVE_FLASH 148
#define MOVE_PSYWAVE 149
#define MOVE_SPLASH 150
#define MOVE_NEW_HOPPING_AROUND MOVE_SPLASH // TNDYS
#define MOVE_ACID_ARMOR 151
#define MOVE_NEW_DISPERSE MOVE_ACID_ARMOR // TNDYS
#define MOVE_CRABHAMMER 152
#define MOVE_NEW_GUTS_PUNCH MOVE_CRABHAMMER // TNDYS
#define MOVE_EXPLOSION 153
#define MOVE_FURY_SWIPES 154
#define MOVE_BONEMERANG 155
#define MOVE_NEW_BOOMERANG MOVE_BONEMERANG // TNDYS
#define MOVE_REST 156
#define MOVE_ROCK_SLIDE 157
#define MOVE_NEW_STONE_RAIN MOVE_ROCK_SLIDE // TNDYS
#define MOVE_HYPER_FANG 158
#define MOVE_NEW_KILLING_BITE MOVE_HYPER_FANG // TNDYS
#define MOVE_SHARPEN 159
#define MOVE_CONVERSION 160
#define MOVE_TRI_ATTACK 161
#define MOVE_SUPER_FANG 162
#define MOVE_NEW_HEAT_CLAW MOVE_SUPER_FANG // TNDYS
#define MOVE_SLASH 163
#define MOVE_SUBSTITUTE 164
#define MOVE_STRUGGLE 165

#define MOVES_COUNT_GEN1 166

#define MOVE_SKETCH 166
#define MOVE_TRIPLE_KICK 167
#define MOVE_THIEF 168
#define MOVE_SPIDER_WEB 169
#define MOVE_MIND_READER 170
#define MOVE_NEW_HEARTS_EYE MOVE_MIND_READER // TNDYS
#define MOVE_NIGHTMARE 171
#define MOVE_FLAME_WHEEL 172
#define MOVE_SNORE 173
#define MOVE_CURSE 174
#define MOVE_FLAIL 175
#define MOVE_CONVERSION_2 176
#define MOVE_AEROBLAST 177
#define MOVE_COTTON_SPORE 178
#define MOVE_REVERSAL 179
#define MOVE_SPITE 180
#define MOVE_POWDER_SNOW 181
#define MOVE_PROTECT 182
#define MOVE_MACH_PUNCH 183
#define MOVE_SCARY_FACE 184
#define MOVE_FEINT_ATTACK 185
#define MOVE_FAINT_ATTACK MOVE_FEINT_ATTACK // Pre-Gen VI name
#define MOVE_NEW_SNEAK_ATTACK MOVE_FEINT_ATTACK // TNDYS
#define MOVE_SWEET_KISS 186
#define MOVE_BELLY_DRUM 187
#define MOVE_SLUDGE_BOMB 188
#define MOVE_NEW_CORROSIVE_ACID MOVE_SLUDGE_BOMB // TNDYS
#define MOVE_MUD_SLAP 189
#define MOVE_NEW_MUD_SHOT MOVE_MUD_SLAP // TNDYS
#define MOVE_OCTAZOOKA 190
#define MOVE_NEW_DARK_RIPPLE MOVE_OCTAZOOKA // TNDYS
#define MOVE_SPIKES 191
#define MOVE_ZAP_CANNON 192
#define MOVE_FORESIGHT 193
#define MOVE_DESTINY_BOND 194
#define MOVE_PERISH_SONG 195
#define MOVE_ICY_WIND 196
#define MOVE_NEW_WINTER_BLAST MOVE_ICY_WIND // TNDYS
#define MOVE_DETECT 197
#define MOVE_BONE_RUSH 198
#define MOVE_LOCK_ON 199
#define MOVE_OUTRAGE 200
#define MOVE_SANDSTORM 201
#define MOVE_GIGA_DRAIN 202
#define MOVE_ENDURE 203
#define MOVE_CHARM 204
#define MOVE_NEW_CHARMING_SMILE MOVE_CHARM // TNDYS
#define MOVE_ROLLOUT 205
#define MOVE_NEW_EARTH_TREMOR MOVE_ROLLOUT // TNDYS
#define MOVE_FALSE_SWIPE 206
#define MOVE_NEW_DRAWN_LINE MOVE_FALSE_SWIPE // TNDYS
#define MOVE_SWAGGER 207
#define MOVE_MILK_DRINK 208
#define MOVE_SPARK 209
#define MOVE_FURY_CUTTER 210
#define MOVE_STEEL_WING 211
#define MOVE_MEAN_LOOK 212
#define MOVE_NEW_ENCHANTING_EYES MOVE_MEAN_LOOK // TNDYS
#define MOVE_ATTRACT 213
#define MOVE_SLEEP_TALK 214
#define MOVE_HEAL_BELL 215
#define MOVE_RETURN 216
#define MOVE_NEW_JOY_STRIKE MOVE_RETURN // TNDYS
#define MOVE_PRESENT 217
#define MOVE_NEW_PRANK MOVE_PRESENT // TNDYS
#define MOVE_FRUSTRATION 218
#define MOVE_NEW_ANGSTY_STRIKE MOVE_FRUSTRATION // TNDYS
#define MOVE_SAFEGUARD 219
#define MOVE_PAIN_SPLIT 220
#define MOVE_SACRED_FIRE 221
#define MOVE_MAGNITUDE 222
#define MOVE_DYNAMIC_PUNCH 223
#define MOVE_DYNAMICPUNCH MOVE_DYNAMIC_PUNCH // Pre-Gen VI name
#define MOVE_MEGAHORN 224
#define MOVE_DRAGON_BREATH 225
#define MOVE_DRAGONBREATH MOVE_DRAGON_BREATH // Pre-Gen VI name
#define MOVE_NEW_SPICY_BREATH MOVE_DRAGON_BREATH // TNDYS
#define MOVE_BATON_PASS 226
#define MOVE_ENCORE 227
#define MOVE_PURSUIT 228
#define MOVE_RAPID_SPIN 229
#define MOVE_SWEET_SCENT 230
#define MOVE_NEW_NATURE_POWER MOVE_SWEET_SCENT // TNDYS
#define MOVE_IRON_TAIL 231
#define MOVE_NEW_STEEL_FIST MOVE_IRON_TAIL // TNDYS
#define MOVE_METAL_CLAW 232
#define MOVE_VITAL_THROW 233
#define MOVE_MORNING_SUN 234
#define MOVE_NEW_DIVINE_LIGHT MOVE_MORNING_SUN // TNDYS
#define MOVE_SYNTHESIS 235
#define MOVE_MOONLIGHT 236
#define MOVE_NEW_LUNATIC MOVE_MOONLIGHT // TNDYS
#define MOVE_HIDDEN_POWER 237
#define MOVE_CROSS_CHOP 238
#define MOVE_NEW_AWAKENED_STRIKE MOVE_CROSS_CHOP // TNDYS
#define MOVE_TWISTER 239
#define MOVE_RAIN_DANCE 240
#define MOVE_SUNNY_DAY 241
#define MOVE_CRUNCH 242
#define MOVE_MIRROR_COAT 243
#define MOVE_PSYCH_UP 244
#define MOVE_EXTREME_SPEED 245
#define MOVE_EXTREMESPEED MOVE_EXTREME_SPEED // Pre-Gen VI name
#define MOVE_ANCIENT_POWER 246
#define MOVE_ANCIENTPOWER MOVE_ANCIENT_POWER // Pre-Gen VI name
#define MOVE_SHADOW_BALL 247
#define MOVE_FUTURE_SIGHT 248
#define MOVE_ROCK_SMASH 249
#define MOVE_WHIRLPOOL 250
#define MOVE_BEAT_UP 251

#define MOVES_COUNT_GEN2 252

#define MOVE_FAKE_OUT 252
#define MOVE_UPROAR 253
#define MOVE_NEW_CONCERT_CRUSH MOVE_UPROAR // TNDYS
#define MOVE_STOCKPILE 254
#define MOVE_SPIT_UP 255
#define MOVE_SWALLOW 256
#define MOVE_HEAT_WAVE 257
#define MOVE_HAIL 258
#define MOVE_TORMENT 259
#define MOVE_FLATTER 260
#define MOVE_WILL_O_WISP 261
#define MOVE_MEMENTO 262
#define MOVE_FACADE 263
#define MOVE_FOCUS_PUNCH 264
#define MOVE_SMELLING_SALTS 265
#define MOVE_SMELLINGSALT MOVE_SMELLING_SALTS // Pre-Gen VI name
#define MOVE_FOLLOW_ME 266
#define MOVE_NATURE_POWER 267
#define MOVE_NEW_ROCK_BULLET MOVE_NATURE_POWER // TNDYS
#define MOVE_CHARGE 268
#define MOVE_TAUNT 269
#define MOVE_HELPING_HAND 270
#define MOVE_TRICK 271
#define MOVE_ROLE_PLAY 272
#define MOVE_NEW_RECOLLECTION MOVE_ROLE_PLAY // TNDYS
#define MOVE_WISH 273
#define MOVE_ASSIST 274
#define MOVE_INGRAIN 275
#define MOVE_SUPERPOWER 276
#define MOVE_MAGIC_COAT 277
#define MOVE_RECYCLE 278
#define MOVE_REVENGE 279
#define MOVE_BRICK_BREAK 280
#define MOVE_YAWN 281
#define MOVE_KNOCK_OFF 282
#define MOVE_ENDEAVOR 283
#define MOVE_ERUPTION 284
#define MOVE_SKILL_SWAP 285
#define MOVE_IMPRISON 286
#define MOVE_REFRESH 287
#define MOVE_GRUDGE 288
#define MOVE_NEW_SHADOW_DANCE MOVE_GRUDGE // TNDYS
#define MOVE_SNATCH 289
#define MOVE_SECRET_POWER 290
#define MOVE_DIVE 291
#define MOVE_ARM_THRUST 292
#define MOVE_NEW_DIVINE_PALM MOVE_ARM_THRUST // TNDYS
#define MOVE_CAMOUFLAGE 293
#define MOVE_TAIL_GLOW 294
#define MOVE_NEW_MANA_CHARGE MOVE_TAIL_GLOW // TNDYS
#define MOVE_LUSTER_PURGE 295
#define MOVE_NEW_FANTASY_HEAVEN MOVE_LUSTER_PURGE // TNDYS
#define MOVE_MIST_BALL 296
#define MOVE_FEATHER_DANCE 297
#define MOVE_FEATHERDANCE MOVE_FEATHER_DANCE // Pre-Gen VI name
#define MOVE_TEETER_DANCE 298
#define MOVE_BLAZE_KICK 299
#define MOVE_MUD_SPORT 300
#define MOVE_NEW_MUD_SPRAY MOVE_MUD_SPORT // TNDYS
#define MOVE_ICE_BALL 301
#define MOVE_NEEDLE_ARM 302
#define MOVE_SLACK_OFF 303
#define MOVE_HYPER_VOICE 304
#define MOVE_POISON_FANG 305
#define MOVE_CRUSH_CLAW 306
#define MOVE_BLAST_BURN 307
#define MOVE_HYDRO_CANNON 308
#define MOVE_METEOR_MASH 309
#define MOVE_ASTONISH 310
#define MOVE_WEATHER_BALL 311
#define MOVE_AROMATHERAPY 312
#define MOVE_FAKE_TEARS 313
#define MOVE_NEW_CROCODILE_TEARS MOVE_FAKE_TEARS // TNDYS
#define MOVE_AIR_CUTTER 314
#define MOVE_OVERHEAT 315
#define MOVE_ODOR_SLEUTH 316
#define MOVE_NEW_SHADOW_CLONE MOVE_ODOR_SLEUTH // TNDYS
#define MOVE_ROCK_TOMB 317
#define MOVE_SILVER_WIND 318
#define MOVE_METAL_SOUND 319
#define NEW_MOVE_BINDING_VOICE MOVE_METAL_SOUND // TNDYS
#define MOVE_GRASS_WHISTLE 320
#define MOVE_GRASSWHISTLE MOVE_GRASS_WHISTLE // Pre-Gen VI name
#define MOVE_NEW_NATURE_TIMBRE MOVE_GRASS_WHISTLE // TNDYS
#define MOVE_TICKLE 321
#define MOVE_COSMIC_POWER 322
#define MOVE_WATER_SPOUT 323
#define MOVE_NEW_WATER_SHOWER MOVE_WATER_SPOUT // TNDYS
#define MOVE_SIGNAL_BEAM 324
#define MOVE_SHADOW_PUNCH 325
#define MOVE_EXTRASENSORY 326
#define MOVE_SKY_UPPERCUT 327
#define MOVE_NEW_SOAR MOVE_SKY_UPPERCUT // TNDYS
#define MOVE_SAND_TOMB 328
#define MOVE_SHEER_COLD 329
#define MOVE_MUDDY_WATER 330
#define MOVE_BULLET_SEED 331
#define MOVE_AERIAL_ACE 332
#define MOVE_NEW_SWALLOW_RETURN MOVE_AERIAL_ACE // TNDYS
#define MOVE_ICICLE_SPEAR 333
#define MOVE_IRON_DEFENSE 334
#define MOVE_BLOCK 335
#define MOVE_HOWL 336
#define MOVE_DRAGON_CLAW 337
#define MOVE_FRENZY_PLANT 338
#define MOVE_BULK_UP 339
#define MOVE_BOUNCE 340
#define MOVE_MUD_SHOT 341
#define NEW_MOVE_MUD_TURRET MOVE_MUD_SHOT // TNDYS
#define MOVE_POISON_TAIL 342
#define MOVE_NEW_POISON_BLADE MOVE_POISON_TAIL // TNDYS
#define MOVE_COVET 343
#define MOVE_VOLT_TACKLE 344
#define MOVE_MAGICAL_LEAF 345
#define MOVE_WATER_SPORT 346
#define MOVE_NEW_SPLASH MOVE_WATER_SPORT // TNDYS
#define MOVE_CALM_MIND 347
#define MOVE_LEAF_BLADE 348
#define MOVE_DRAGON_DANCE 349
#define MOVE_NEW_TACTICAL_DANCE MOVE_DRAGON_DANCE // TNDYS
#define MOVE_ROCK_BLAST 350
#define MOVE_SHOCK_WAVE 351
#define MOVE_WATER_PULSE 352
#define MOVE_DOOM_DESIRE 353
#define MOVE_PSYCHO_BOOST 354

#define MOVES_COUNT_GEN3 355

// Gen 4 moves.
#define MOVE_ROOST 355
#define MOVE_GRAVITY 356
#define MOVE_MIRACLE_EYE 357
#define MOVE_WAKE_UP_SLAP 358
#define MOVE_HAMMER_ARM 359
#define MOVE_GYRO_BALL 360
#define MOVE_NEW_TORNADO_SPHERE MOVE_GYRO_BALL // TNDYS
#define MOVE_HEALING_WISH 361
#define MOVE_BRINE 362
#define MOVE_NATURAL_GIFT 363
#define MOVE_NEW_FRUIT_PUNCH MOVE_NATURAL_GIFT // TNDYS
#define MOVE_FEINT 364
#define MOVE_PLUCK 365
#define MOVE_NEW_SNACK_STEAL MOVE_PLUCK // TNDYS
#define MOVE_TAILWIND 366
#define MOVE_ACUPRESSURE 367
#define MOVE_NEW_PRESSURE_NEEDLE MOVE_ACUPRESSURE // TNDYS
#define MOVE_METAL_BURST 368
#define MOVE_NEW_MIRROR_FORCE MOVE_METAL_BURST // TNDYS
#define MOVE_U_TURN 369
#define MOVE_CLOSE_COMBAT 370
#define MOVE_PAYBACK 371
#define MOVE_ASSURANCE 372
#define MOVE_EMBARGO 373
#define MOVE_FLING 374
#define MOVE_PSYCHO_SHIFT 375
#define MOVE_TRUMP_CARD 376
#define MOVE_HEAL_BLOCK 377
#define MOVE_WRING_OUT 378
#define MOVE_POWER_TRICK 379
#define MOVE_GASTRO_ACID 380
#define MOVE_NEW_NULL_MEDICINE MOVE_GASTRO_ACID // TNDYS
#define MOVE_LUCKY_CHANT 381
#define MOVE_ME_FIRST 382
#define MOVE_COPYCAT 383
#define MOVE_POWER_SWAP 384
#define MOVE_GUARD_SWAP 385
#define MOVE_PUNISHMENT 386
#define MOVE_LAST_RESORT 387
#define MOVE_WORRY_SEED 388
#define MOVE_SUCKER_PUNCH 389
#define MOVE_TOXIC_SPIKES 390
#define MOVE_HEART_SWAP 391
#define MOVE_AQUA_RING 392
#define MOVE_NEW_HEALING_RING MOVE_AQUA_RING // TNDYS
#define MOVE_MAGNET_RISE 393
#define MOVE_FLARE_BLITZ 394
#define MOVE_FORCE_PALM 395
#define MOVE_AURA_SPHERE 396
#define MOVE_ROCK_POLISH 397
#define MOVE_POISON_JAB 398
#define MOVE_DARK_PULSE 399
#define MOVE_NIGHT_SLASH 400
#define MOVE_NEW_RULE_BREAKER MOVE_NIGHT_SLASH // TNDYS
#define MOVE_AQUA_TAIL 401
#define MOVE_SEED_BOMB 402
#define MOVE_AIR_SLASH 403
#define MOVE_X_SCISSOR 404
#define MOVE_BUG_BUZZ 405
#define MOVE_NEW_THREATENING_ROAR MOVE_BUG_BUZZ // TNDYS
#define MOVE_DRAGON_PULSE 406
#define MOVE_NEW_PULSE_WAVE MOVE_DRAGON_PULSE // TNDYS
#define MOVE_DRAGON_RUSH 407
#define MOVE_NEW_IMPACT_RUSH MOVE_DRAGON_RUSH // TNDYS
#define MOVE_POWER_GEM 408
#define MOVE_DRAIN_PUNCH 409
#define MOVE_VACUUM_WAVE 410
#define MOVE_FOCUS_BLAST 411
#define MOVE_ENERGY_BALL 412
#define MOVE_BRAVE_BIRD 413
#define MOVE_EARTH_POWER 414
#define MOVE_SWITCHEROO 415
#define MOVE_GIGA_IMPACT 416
#define MOVE_NASTY_PLOT 417
#define MOVE_BULLET_PUNCH 418
#define MOVE_AVALANCHE 419
#define MOVE_ICE_SHARD 420
#define MOVE_SHADOW_CLAW 421
#define MOVE_THUNDER_FANG 422
#define MOVE_ICE_FANG 423
#define MOVE_FIRE_FANG 424
#define MOVE_SHADOW_SNEAK 425
#define MOVE_MUD_BOMB 426
#define MOVE_PSYCHO_CUT 427
#define MOVE_ZEN_HEADBUTT 428
#define MOVE_MIRROR_SHOT 429
#define MOVE_FLASH_CANNON 430
#define MOVE_ROCK_CLIMB 431
#define MOVE_DEFOG 432
#define MOVE_TRICK_ROOM 433
#define MOVE_DRACO_METEOR 434
#define MOVE_NEW_METEOR_STREAM MOVE_DRACO_METEOR // TNDYS
#define MOVE_DISCHARGE 435
#define MOVE_LAVA_PLUME 436
#define MOVE_LEAF_STORM 437
#define MOVE_POWER_WHIP 438
#define MOVE_ROCK_WRECKER 439
#define MOVE_CROSS_POISON 440
#define MOVE_GUNK_SHOT 441
#define MOVE_IRON_HEAD 442
#define MOVE_MAGNET_BOMB 443
#define MOVE_STONE_EDGE 444
#define MOVE_CAPTIVATE 445
#define MOVE_NEW_LOVELY_ATTACK MOVE_CAPTIVATE // TNDYS
#define MOVE_STEALTH_ROCK 446
#define MOVE_NEW_STEALTH_TUSK MOVE_STEALTH_ROCK // TNDYS
#define MOVE_GRASS_KNOT 447
#define MOVE_NEW_PENETRATION_ROOT MOVE_GRASS_KNOT // TNDYS
#define MOVE_CHATTER 448
#define MOVE_NEW_NIGHT_CHIRP MOVE_CHATTER // TNDYS
#define MOVE_JUDGMENT 449
#define MOVE_BUG_BITE 450
#define MOVE_CHARGE_BEAM 451
#define MOVE_WOOD_HAMMER 452
#define MOVE_AQUA_JET 453
#define MOVE_ATTACK_ORDER 454
#define MOVE_DEFEND_ORDER 455
#define MOVE_HEAL_ORDER 456
#define MOVE_HEAD_SMASH 457
#define MOVE_DOUBLE_HIT 458
#define MOVE_ROAR_OF_TIME 459
#define MOVE_NEW_TIME_JUDGEMENT MOVE_ROAR_OF_TIME // TNDYS
#define MOVE_SPACIAL_REND 460
#define MOVE_LUNAR_DANCE 461
#define MOVE_CRUSH_GRIP 462
#define MOVE_MAGMA_STORM 463
#define MOVE_NEW_MAGMA_TORNADO MOVE_MAGMA_STORM // TNDYS
#define MOVE_DARK_VOID 464
#define MOVE_SEED_FLARE 465
#define MOVE_OMINOUS_WIND 466
#define MOVE_SHADOW_FORCE 467
#define MOVE_NEW_SHADOW_DIVE MOVE_SHADOW_FORCE // TNDYS

#define MOVES_COUNT_GEN4 468

// Gen 5 moves.
#define MOVE_HONE_CLAWS 468
#define MOVE_WIDE_GUARD 469
#define MOVE_GUARD_SPLIT 470
#define MOVE_POWER_SPLIT 471
#define MOVE_WONDER_ROOM 472
#define MOVE_PSYSHOCK 473
#define MOVE_VENOSHOCK 474
#define MOVE_AUTOTOMIZE 475
#define MOVE_NEW_CAST_OFF MOVE_AUTOTOMIZE // TNDYS
#define MOVE_RAGE_POWDER 476
#define MOVE_TELEKINESIS 477
#define MOVE_MAGIC_ROOM 478
#define MOVE_SMACK_DOWN 479
#define MOVE_NEW_SHOT_DOWN MOVE_SMACK_DOWN // TNDYS
#define MOVE_STORM_THROW 480
#define MOVE_FLAME_BURST 481
#define MOVE_SLUDGE_WAVE 482
#define MOVE_QUIVER_DANCE 483
#define MOVE_HEAVY_SLAM 484
#define MOVE_NEW_CHARISMA_BLOW MOVE_HEAVY_SLAM // TNDYS
#define MOVE_SYNCHRONOISE 485
#define MOVE_NEW_SYNCHRONIC_HEART MOVE_SYNCHRONOISE // TNDYS
#define MOVE_ELECTRO_BALL 486
#define MOVE_SOAK 487
#define MOVE_FLAME_CHARGE 488
#define MOVE_COIL 489
#define MOVE_LOW_SWEEP 490
#define MOVE_ACID_SPRAY 491
#define MOVE_FOUL_PLAY 492
#define MOVE_SIMPLE_BEAM 493
#define MOVE_ERRATIC_BEAM MOVE_SIMPLE_BEAM // TNDYS
#define MOVE_ENTRAINMENT 494
#define MOVE_AFTER_YOU 495
#define MOVE_NEW_DOUBLE_TROUBLE MOVE_AFTER_YOU // TNDYS
#define MOVE_ROUND 496
#define MOVE_NEW_SING_A_LONG MOVE_ROUND // TNDYS
#define MOVE_ECHOED_VOICE 497
#define MOVE_CHIP_AWAY 498
#define MOVE_CLEAR_SMOG 499
#define MOVE_NEW_CLEAR_MIST MOVE_CLEAR_SMOG // TNDYS
#define MOVE_STORED_POWER 500
#define MOVE_QUICK_GUARD 501
#define MOVE_ALLY_SWITCH 502
#define MOVE_SCALD 503
#define MOVE_SHELL_SMASH 504
#define MOVE_HEAL_PULSE 505
#define MOVE_HEX 506
#define MOVE_SKY_DROP 507
#define MOVE_SHIFT_GEAR 508
#define MOVE_CIRCLE_THROW 509
#define MOVE_INCINERATE 510
#define MOVE_QUASH 511
#define MOVE_NEW_OPPRESSION MOVE_QUASH // TNDYS
#define MOVE_ACROBATICS 512
#define MOVE_REFLECT_TYPE 513
#define MOVE_RETALIATE 514
#define MOVE_FINAL_GAMBIT 515
#define MOVE_NEW_LIFE_SACRIFICE MOVE_FINAL_GAMBIT // TNDYS
#define MOVE_BESTOW 516
#define MOVE_ITEM_PASS MOVE_BESTOW // TNDYS
#define MOVE_INFERNO 517
#define MOVE_WATER_PLEDGE 518
#define MOVE_FIRE_PLEDGE 519
#define MOVE_GRASS_PLEDGE 520
#define MOVE_NATURE_PLEDGE MOVE_GRASS_PLEDGE // TNDYS
#define MOVE_VOLT_SWITCH 521
#define MOVE_STRUGGLE_BUG 522
#define MOVE_NEW_CORNERED_CAT MOVE_STRUGGLE_BUG // TNDYS
#define MOVE_BULLDOZE 523
#define MOVE_FROST_BREATH 524
#define MOVE_DRAGON_TAIL 525
#define MOVE_NEW_IMPACT_BLOW MOVE_DRAGON_TAIL // TNDYS
#define MOVE_WORK_UP 526
#define MOVE_NEW_WARCRY MOVE_WORK_UP // TNDYS
#define MOVE_ELECTROWEB 527
#define MOVE_WILD_CHARGE 528
#define MOVE_NEW_BOLT_HAMMER MOVE_WILD_CHARGE // TNDYS
#define MOVE_DRILL_RUN 529
#define MOVE_NEW_CYCLONE_BULLET MOVE_DRILL_RUN // TNDYS
#define MOVE_DUAL_CHOP 530
#define MOVE_NEW_CHOMP_CHOMP MOVE_DUAL_CHOP // TNDYS
#define MOVE_HEART_STAMP 531
#define MOVE_HORN_LEECH 532
#define MOVE_NEW_DRAINING_STAB MOVE_HORN_LEECH // TNDYS
#define MOVE_SACRED_SWORD 533
#define MOVE_RAZOR_SHELL 534
#define MOVE_HEAT_CRASH 535
#define MOVE_LEAF_TORNADO 536
#define MOVE_STEAMROLLER 537
#define MOVE_COTTON_GUARD 538
#define MOVE_NIGHT_DAZE 539
#define MOVE_PSYSTRIKE 540
#define MOVE_TAIL_SLAP 541
#define MOVE_NEW_RAZOR_WING MOVE_TAIL_SLAP // TNDYS
#define MOVE_HURRICANE 542
#define MOVE_HEAD_CHARGE 543
#define MOVE_GEAR_GRIND 544
#define MOVE_SEARING_SHOT 545
#define MOVE_NEW_RAIL_GUN MOVE_SEARING_SHOT // TNDYS
#define MOVE_TECHNO_BLAST 546
#define MOVE_RELIC_SONG 547
#define MOVE_SECRET_SWORD 548
#define MOVE_GLACIATE 549
#define MOVE_BOLT_STRIKE 550
#define MOVE_BLUE_FLARE 551
#define MOVE_FIERY_DANCE 552
#define MOVE_FREEZE_SHOCK 553
#define MOVE_ICE_BURN 554
#define MOVE_SNARL 555
#define MOVE_ICICLE_CRASH 556
#define MOVE_V_CREATE 557
#define MOVE_NEW_VICTORY_FINALE MOVE_V_CREATE // TNDYS
#define MOVE_FUSION_FLARE 558
#define MOVE_FUSION_BOLT 559

#define MOVES_COUNT_GEN5 560

// Gen 6 moves.
#define MOVE_FLYING_PRESS 560
#define MOVE_NEW_FLYING_IMPACT MOVE_FLYING_PRESS // TNDYS
#define MOVE_MAT_BLOCK 561
#define MOVE_BELCH 562
#define MOVE_ROTOTILLER 563
#define MOVE_STICKY_WEB 564
#define MOVE_FELL_STINGER 565
#define MOVE_NEW_SPIKING_FINISH MOVE_FELL_STINGER // TNDYS
#define MOVE_PHANTOM_FORCE 566
#define MOVE_NEW_SHADOW_SLIP MOVE_PHANTOM_FORCE // TNDYS
#define MOVE_TRICK_OR_TREAT 567
#define MOVE_NEW_HOLLOWFICATION MOVE_TRICK_OR_TREAT // TNDYS
#define MOVE_NOBLE_ROAR 568
#define MOVE_ION_DELUGE 569
#define MOVE_NEW_PLASMA_SHOWER MOVE_ION_DELUGE // TNDYS
#define MOVE_PARABOLIC_CHARGE 570
#define MOVE_FORESTS_CURSE 571
#define MOVE_PETAL_BLIZZARD 572
#define MOVE_NEW_SAKURA_CYCLONE MOVE_PETAL_BLIZZARD // TNDYS
#define MOVE_FREEZE_DRY 573
#define MOVE_DISARMING_VOICE 574
#define MOVE_PARTING_SHOT 575
#define MOVE_TOPSY_TURVY 576
#define MOVE_DRAINING_KISS 577
#define MOVE_CRAFTY_SHIELD 578
#define MOVE_NEW_STATUS_BARRIER MOVE_CRAFTY_SHIELD // TNDYS
#define MOVE_FLOWER_SHIELD 579
#define MOVE_GRASSY_TERRAIN 580
#define MOVE_MISTY_TERRAIN 581
#define MOVE_ELECTRIFY 582
#define MOVE_PLAY_ROUGH 583
#define MOVE_FAIRY_WIND 584
#define MOVE_MOONBLAST 585
#define MOVE_BOOMBURST 586
#define MOVE_NEW_SONIC_BURST MOVE_BOOMBURST // TNDYS
#define MOVE_FAIRY_LOCK 587
#define MOVE_NEW_HEART_LOCK MOVE_FAIRY_LOCK // TNDYS
#define MOVE_KINGS_SHIELD 588
#define MOVE_NEW_KLEIN_FIELD MOVE_KINGS_SHIELD // TNDYS
#define MOVE_PLAY_NICE 589
#define MOVE_CONFIDE 590
#define MOVE_DIAMOND_STORM 591
#define MOVE_STEAM_ERUPTION 592
#define MOVE_HYPERSPACE_HOLE 593
#define MOVE_WATER_SHURIKEN 594
#define MOVE_MYSTICAL_FIRE 595
#define MOVE_SPIKY_SHIELD 596
#define MOVE_AROMATIC_MIST 597
#define MOVE_EERIE_IMPULSE 598
#define MOVE_VENOM_DRENCH 599
#define MOVE_POWDER 600
#define MOVE_GEOMANCY 601
#define MOVE_MAGNETIC_FLUX 602
#define MOVE_HAPPY_HOUR 603
#define MOVE_ELECTRIC_TERRAIN 604
#define MOVE_NEW_ELECTRIC_FIELD MOVE_ELECTRIC_TERRAIN // TNDYS
#define MOVE_DAZZLING_GLEAM 605
#define MOVE_CELEBRATE 606
#define MOVE_HOLD_HANDS 607
#define MOVE_BABY_DOLL_EYES 608
#define MOVE_NUZZLE 609
#define MOVE_HOLD_BACK 610
#define MOVE_INFESTATION 611
#define MOVE_POWER_UP_PUNCH 612
#define MOVE_OBLIVION_WING 613
#define MOVE_THOUSAND_ARROWS 614
#define MOVE_THOUSAND_WAVES 615
#define MOVE_LANDS_WRATH 616
#define MOVE_LIGHT_OF_RUIN 617
// ORAS Moves
#define MOVE_ORIGIN_PULSE 618
#define MOVE_PRECIPICE_BLADES 619
#define MOVE_DRAGON_ASCENT 620
#define MOVE_NEW_DRAGON_DIVE MOVE_DRAGON_ASCENT // TNDYS
#define MOVE_HYPERSPACE_FURY 621

#define MOVES_COUNT_GEN6 622

// Gen 7 moves.
#define MOVE_SHORE_UP 622
#define MOVE_NEW_SAND_HEALING MOVE_SHORE_UP // TNDYS
#define MOVE_FIRST_IMPRESSION 623
#define MOVE_BANEFUL_BUNKER 624
#define MOVE_SPIRIT_SHACKLE 625
#define MOVE_DARKEST_LARIAT 626
#define MOVE_SPARKLING_ARIA 627
#define MOVE_ICE_HAMMER 628
#define MOVE_FLORAL_HEALING 629
#define MOVE_HIGH_HORSEPOWER 630
#define MOVE_NEW_ENIGMATIC_KICK MOVE_HIGH_HORSEPOWER // TNDYS
#define MOVE_STRENGTH_SAP 631
#define MOVE_SOLAR_BLADE 632
#define MOVE_LEAFAGE 633
#define MOVE_SPOTLIGHT 634
#define MOVE_TOXIC_THREAD 635
#define MOVE_LASER_FOCUS 636
#define MOVE_NEW_STARRING_DAGGER MOVE_LASER_FOCUS // TNDYS
#define MOVE_GEAR_UP 637
#define MOVE_THROAT_CHOP 638
#define MOVE_POLLEN_PUFF 639
#define MOVE_ANCHOR_SHOT 640
#define MOVE_PSYCHIC_TERRAIN 641
#define MOVE_NEW_MAGIC_FIELD MOVE_PSYCHIC_TERRAIN // TNDYS
#define MOVE_LUNGE 642
#define MOVE_FIRE_LASH 643
#define MOVE_POWER_TRIP 644
#define MOVE_BURN_UP 645
#define MOVE_SPEED_SWAP 646
#define MOVE_SMART_STRIKE 647
#define MOVE_PURIFY 648
#define MOVE_REVELATION_DANCE 649
#define MOVE_CORE_ENFORCER 650
#define MOVE_NEW_PURIFICATION_RAY MOVE_CORE_ENFORCER // TNDYS
#define MOVE_TROP_KICK 651
#define MOVE_NEW_MAJESTIC_KICK MOVE_TROP_KICK // TNDYS
#define MOVE_INSTRUCT 652
#define MOVE_BEAK_BLAST 653
#define MOVE_NEW_BURNING_FEATHER MOVE_BEAK_BLAST // TNDYS
#define MOVE_CLANGING_SCALES 654
#define MOVE_DRAGON_HAMMER 655
#define MOVE_NEW_BRUTAL_CLUB MOVE_DRAGON_HAMMER // TNDYS
#define MOVE_BRUTAL_SWING 656
#define MOVE_NEW_HEAVY_ROTATION MOVE_BRUTAL_SWING // TNDYS
#define MOVE_AURORA_VEIL 657
#define MOVE_SHELL_TRAP 658
#define MOVE_NEW_COUNTER_MISSILE MOVE_SHELL_TRAP // TNDYS
#define MOVE_FLEUR_CANNON 659
#define MOVE_PSYCHIC_FANGS 660
#define MOVE_NEW_MAGIC_FANGS MOVE_PSYCHIC_FANGS // TNDYS
#define MOVE_STOMPING_TANTRUM 661
#define MOVE_SHADOW_BONE 662
#define MOVE_NEW_SHADOW_CLUB MOVE_SHADOW_BONE // TNDYS
#define MOVE_ACCELEROCK 663
#define MOVE_NEW_ROCK_TURBO MOVE_ACCELEROCK // TNDYS
#define MOVE_LIQUIDATION 664
#define MOVE_NEW_AQUA_BREAK MOVE_LIQUIDATION // TNDYS
#define MOVE_PRISMATIC_LASER 665
#define MOVE_SPECTRAL_THIEF 666
#define MOVE_SUNSTEEL_STRIKE 667
#define MOVE_NEW_COMPLETE_SMASH MOVE_SUNSTEEL_STRIKE // TNDYS
#define MOVE_MOONGEIST_BEAM 668
#define MOVE_TEARFUL_LOOK 669
#define MOVE_ZING_ZAP 670
#define MOVE_NATURES_MADNESS 671
#define MOVE_MULTI_ATTACK 672
#define MOVE_NEW_PROJECTION_PUNCH MOVE_MULTI_ATTACK // TNDYS
// USUM Moves
#define MOVE_MIND_BLOWN 673
#define MOVE_PLASMA_FISTS 674
#define MOVE_PHOTON_GEYSER 675
#define MOVE_SDF_MAIN_GUN MOVE_PHOTON_GEYSER // TNDYS
// LGPE Moves
#define MOVE_ZIPPY_ZAP 676
#define MOVE_SPLISHY_SPLASH 677
#define MOVE_FLOATY_FALL 678
#define MOVE_PIKA_PAPOW 679
#define MOVE_NEW_LOYAL_SNUGGLE MOVE_PIKA_PAPOW // TNDYS
#define MOVE_BOUNCY_BUBBLE 680
#define MOVE_BUZZY_BUZZ 681
#define MOVE_SIZZLY_SLIDE 682
#define MOVE_GLITZY_GLOW 683
#define MOVE_BADDY_BAD 684
#define MOVE_SAPPY_SEED 685
#define MOVE_NEW_VAMPIRE_SEED MOVE_SAPPY_SEED // TNDYS
#define MOVE_FREEZY_FROST 686
#define MOVE_SPARKLY_SWIRL 687
#define MOVE_VEEVEE_VOLLEY 688
#define MOVE_NEW_LOYAL_VOLLEY MOVE_VEEVEE_VOLLEY // TNDYS
#define MOVE_DOUBLE_IRON_BASH 689

#define MOVES_COUNT_GEN7 690

// Gen 8 moves.
#define MOVE_DYNAMAX_CANNON 690
#define MOVE_NEW_CHAOS_CANNON MOVE_DYNAMAX_CANNON // TNDYS
#define MOVE_SNIPE_SHOT 691
#define MOVE_JAW_LOCK 692
#define MOVE_STUFF_CHEEKS 693
#define MOVE_NO_RETREAT 694
#define MOVE_TAR_SHOT 695
#define MOVE_MAGIC_POWDER 696
#define MOVE_DRAGON_DARTS 697
#define MOVE_NEW_SACRED_NEEDLES MOVE_DRAGON_DARTS // TNDYS
#define MOVE_TEATIME 698
#define MOVE_OCTOLOCK 699
#define MOVE_NEW_PHANTOM_LOCK MOVE_OCTOLOCK // TNDYS
#define MOVE_BOLT_BEAK 700
#define MOVE_NEW_FOCUS_JOLT MOVE_BOLT_BEAK // TNDYS
#define MOVE_FISHIOUS_REND 701
#define MOVE_NEW_VICIOUS_GNAW MOVE_FISHIOUS_REND // TNDYS
#define MOVE_COURT_CHANGE 702
#define MOVE_CLANGOROUS_SOUL 703
#define MOVE_NEW_SOUL_SACRIFICE MOVE_CLANGOROUS_SOUL // TNDYS
#define MOVE_BODY_PRESS 704
#define MOVE_DECORATE 705
#define MOVE_NEW_DRESS_UP MOVE_DECORATE // TNDYS
#define MOVE_DRUM_BEATING 706
#define MOVE_SNAP_TRAP 707
#define MOVE_NEW_BEAR_TRAP MOVE_SNAP_TRAP // TNDYS
#define MOVE_PYRO_BALL 708
#define MOVE_NEW_BLAZING_BALL MOVE_PYRO_BALL // TNDYS
#define MOVE_BEHEMOTH_BLADE 709
#define MOVE_BEHEMOTH_BASH 710
#define MOVE_AURA_WHEEL 711
#define MOVE_BREAKING_SWIPE 712
#define MOVE_BRANCH_POKE 713
#define MOVE_OVERDRIVE 714
#define MOVE_APPLE_ACID 715
#define MOVE_GRAV_APPLE 716
#define MOVE_SPIRIT_BREAK 717
#define MOVE_STRANGE_STEAM 718
#define MOVE_LIFE_DEW 719
#define MOVE_OBSTRUCT 720
#define MOVE_FALSE_SURRENDER 721
#define MOVE_METEOR_ASSAULT 722
#define MOVE_ETERNABEAM 723
#define MOVE_NEW_ETERNAL_BEAM MOVE_ETERNABEAM // TNDYS
#define MOVE_STEEL_BEAM 724
// Isle of Armor Moves
#define MOVE_EXPANDING_FORCE 725
#define MOVE_STEEL_ROLLER 726
#define MOVE_NEW_FIELD_DESTROYER MOVE_STEEL_ROLLER // TNDYS
#define MOVE_SCALE_SHOT 727
#define MOVE_METEOR_BEAM 728
#define MOVE_SHELL_SIDE_ARM 729
#define MOVE_PROFICIENT_ARM MOVE_SHELL_SIDE_ARM // TNDYS
#define MOVE_MISTY_EXPLOSION 730
#define MOVE_NEW_DIVINE_EXPLOSION MOVE_MISTY_EXPLOSION // TNDYS
#define MOVE_GRASSY_GLIDE 731
#define MOVE_RISING_VOLTAGE 732
#define MOVE_TERRAIN_PULSE 733
#define MOVE_NEW_PULSE_OF_NATURE MOVE_TERRAIN_PULSE // TNDYS
#define MOVE_SKITTER_SMACK 734
#define MOVE_BURNING_JEALOUSY 735
#define MOVE_LASH_OUT 736
#define MOVE_POLTERGEIST 737
#define MOVE_CORROSIVE_GAS 738
#define MOVE_COACHING 739
#define MOVE_FLIP_TURN 740
#define MOVE_TRIPLE_AXEL 741
#define MOVE_DUAL_WINGBEAT 742
#define MOVE_SCORCHING_SANDS 743
#define MOVE_JUNGLE_HEALING 744
#define MOVE_WICKED_BLOW 745
#define MOVE_SURGING_STRIKES 746
// Crown Tundra Moves
#define MOVE_THUNDER_CAGE 747
#define MOVE_DRAGON_ENERGY 748
#define MOVE_NEW_FORCE_ENERGY MOVE_DRAGON_ENERGY // TNDYS
#define MOVE_FREEZING_GLARE 749
#define MOVE_FIERY_WRATH 750
#define MOVE_THUNDEROUS_KICK 751
#define MOVE_GLACIAL_LANCE 752
#define MOVE_ASTRAL_BARRAGE 753
#define MOVE_EERIE_SPELL 754
// Legends: Arceus Moves
#define MOVE_DIRE_CLAW 755
#define MOVE_PSYSHIELD_BASH 756
#define MOVE_POWER_SHIFT 757
#define MOVE_STONE_AXE 758
#define MOVE_NEW_CHIPPER_AXE MOVE_STONE_AXE // TNDYS
#define MOVE_SPRINGTIDE_STORM 759
#define MOVE_MYSTICAL_POWER 760
#define MOVE_RAGING_FURY 761
#define MOVE_WAVE_CRASH 762
#define MOVE_CHLOROBLAST 763
#define MOVE_MOUNTAIN_GALE 764
#define MOVE_VICTORY_DANCE 765
#define MOVE_HEADLONG_RUSH 766
#define MOVE_BARB_BARRAGE 767
#define MOVE_ESPER_WING 768
#define MOVE_BITTER_MALICE 769
#define MOVE_SHELTER 770
#define MOVE_TRIPLE_ARROWS 771
#define MOVE_NEW_ARROW_WINGS MOVE_TRIPLE_ARROWS // TNDYS
#define MOVE_INFERNAL_PARADE 772
#define MOVE_CEASELESS_EDGE 773
#define MOVE_BLEAKWIND_STORM 774
#define MOVE_WILDBOLT_STORM 775
#define MOVE_SANDSEAR_STORM 776
#define MOVE_LUNAR_BLESSING 777
#define MOVE_TAKE_HEART 778

#define MOVES_COUNT_GEN8 779

// Gen 9 moves.
#define MOVE_TERA_BLAST 779
#define MOVE_SILK_TRAP 780
#define MOVE_AXE_KICK 781
#define MOVE_LAST_RESPECTS 782
#define MOVE_LUMINA_CRASH 783
#define MOVE_ORDER_UP 784
#define MOVE_JET_PUNCH 785
#define MOVE_SPICY_EXTRACT 786
#define MOVE_SPIN_OUT 787
#define MOVE_POPULATION_BOMB 788
#define MOVE_NEW_PAPER_SLICE MOVE_POPULATION_BOMB // TNDYS
#define MOVE_ICE_SPINNER 789
#define MOVE_GLAIVE_RUSH 790
#define MOVE_REVIVAL_BLESSING 791
#define MOVE_SALT_CURE 792
#define MOVE_TRIPLE_DIVE 793
#define MOVE_MORTAL_SPIN 794
#define MOVE_DOODLE 795
#define MOVE_FILLET_AWAY 796
#define MOVE_KOWTOW_CLEAVE 797
#define MOVE_FLOWER_TRICK 798
#define MOVE_TORCH_SONG 799
#define MOVE_AQUA_STEP 800
#define MOVE_RAGING_BULL 801
#define MOVE_MAKE_IT_RAIN 802
#define MOVE_RUINATION 803
#define MOVE_COLLISION_COURSE 804
#define MOVE_ELECTRO_DRIFT 805
#define MOVE_SHED_TAIL 806
#define MOVE_CHILLY_RECEPTION 807
#define MOVE_TIDY_UP 808
#define MOVE_SNOWSCAPE 809
#define MOVE_POUNCE 810
#define MOVE_TRAILBLAZE 811
#define MOVE_CHILLING_WATER 812
#define MOVE_HYPER_DRILL 813
#define MOVE_TWIN_BEAM 814
#define MOVE_RAGE_FIST 815
#define MOVE_ARMOR_CANNON 816
#define MOVE_BITTER_BLADE 817
#define MOVE_DOUBLE_SHOCK 818
#define MOVE_GIGATON_HAMMER 819
#define MOVE_COMEUPPANCE 820
#define MOVE_AQUA_CUTTER 821
#define MOVE_BLAZING_TORQUE 822
#define MOVE_WICKED_TORQUE 823
#define MOVE_NOXIOUS_TORQUE 824
#define MOVE_COMBAT_TORQUE 825
#define MOVE_MAGICAL_TORQUE 826
#define MOVE_PSYBLADE 827
#define MOVE_HYDRO_STEAM 828
// The Teal Mask Moves
#define MOVE_BLOOD_MOON 829
#define MOVE_MATCHA_GOTCHA 830
#define MOVE_SYRUP_BOMB 831
#define MOVE_IVY_CUDGEL 832
// The Indigo Disk Moves
#define MOVE_ELECTRO_SHOT 833
#define MOVE_TERA_STARSTORM 834
#define MOVE_FICKLE_BEAM 835
#define MOVE_BURNING_BULWARK 836
#define MOVE_THUNDERCLAP 837
#define MOVE_MIGHTY_CLEAVE 838
#define MOVE_TACHYON_CUTTER 839
#define MOVE_HARD_PRESS 840
#define MOVE_DRAGON_CHEER 841
#define MOVE_NEW_CHEER_DREAMER MOVE_DRAGON_CHEER // TNDYS
#define MOVE_ALLURING_VOICE 842
#define MOVE_TEMPER_FLARE 843
#define MOVE_SUPERCELL_SLAM 844
#define MOVE_PSYCHIC_NOISE 845
#define MOVE_UPPER_HAND 846
#define MOVE_MALIGNANT_CHAIN 847

#define MOVE_END_OFFICIAL          MOVE_MALIGNANT_CHAIN

#define MOVE_ULTRA_INSTINCT         (MOVE_END_OFFICIAL + 1)
#define MOVE_RIDE_TRANSFORM         (MOVE_END_OFFICIAL + 2)
#define MOVE_TWIN_SPARK             (MOVE_END_OFFICIAL + 3)
#define MOVE_DIMENSION_KICK         (MOVE_END_OFFICIAL + 4)
#define MOVE_DIMENSION_SHOT         (MOVE_END_OFFICIAL + 5)
#define MOVE_FLUFFICATION           (MOVE_END_OFFICIAL + 6)
#define MOVE_ILLUSIONARY_DOMINATION (MOVE_END_OFFICIAL + 7)
#define MOVE_SPIRIT_CAMERA          (MOVE_END_OFFICIAL + 8)
#define MOVE_RAGING_DEMON           (MOVE_END_OFFICIAL + 9)
#define MOVE_IDOLA_DIABOLUS         (MOVE_END_OFFICIAL + 10)
#define MOVE_PLASMA_BLADE           (MOVE_END_OFFICIAL + 11)
#define MOVE_BINARY_CRUSHER         (MOVE_END_OFFICIAL + 12)
#define MOVE_DIMENSION_SLASH        (MOVE_END_OFFICIAL + 13)
#define MOVE_NEPTUNE_BREAK          (MOVE_END_OFFICIAL + 14)
#define MOVE_ICE_BLADE              (MOVE_END_OFFICIAL + 15)
#define MOVE_DEFECTIVE_MIRACLE      (MOVE_END_OFFICIAL + 16)
#define MOVE_MIND_HACK              (MOVE_END_OFFICIAL + 17)
#define MOVE_ADVENT_LYCORIS         (MOVE_END_OFFICIAL + 18)
#define MOVE_ADVENT_GERBERA         (MOVE_END_OFFICIAL + 19)
#define MOVE_CHAOS_JUDGMENT         (MOVE_END_OFFICIAL + 20)
#define MOVE_DARKNESS_TERRAIN       (MOVE_END_OFFICIAL + 21)
#define MOVE_QUINTETT_FEUER         (MOVE_END_OFFICIAL + 22)
#define MOVE_UEHEHEHEHEHE           (MOVE_END_OFFICIAL + 23)
#define MOVE_GRIMOIRE_CALL          (MOVE_END_OFFICIAL + 24)
#define MOVE_RAIN_OF_ARROWS         (MOVE_END_OFFICIAL + 25)
#define MOVE_MIASMA_TERRAIN         (MOVE_END_OFFICIAL + 26)
#define MOVE_GAIA_FORCE             (MOVE_END_OFFICIAL + 27)
#define MOVE_POSEIDON_FORCE         (MOVE_END_OFFICIAL + 28)
#define MOVE_ASTROMANCY             (MOVE_END_OFFICIAL + 29)
#define MOVE_WIDE_SLASH             (MOVE_END_OFFICIAL + 30)
#define MOVE_SPIN_SLASH             (MOVE_END_OFFICIAL + 31)
#define MOVE_VACUUM_CUT             (MOVE_END_OFFICIAL + 32)
#define MOVE_FIVE_ELEMENT           (MOVE_END_OFFICIAL + 33)
#define MOVE_STRAWBERRY_CROSS       (MOVE_END_OFFICIAL + 34)
#define MOVE_SPIRIT_BOMB            (MOVE_END_OFFICIAL + 35)
#define MOVE_OMEGA_BLASTER          (MOVE_END_OFFICIAL + 36)
#define MOVE_SUPER_SPIRIT_BOMB      (MOVE_END_OFFICIAL + 37)
#define MOVE_MOCKUP_PHYSICAL_ILLUSION (MOVE_END_OFFICIAL + 38)
#define MOVE_MOCKUP_PHYSICAL_DREAM    (MOVE_END_OFFICIAL + 39)
#define MOVE_MOCKUP_PHYSICAL_FLYING   (MOVE_END_OFFICIAL + 40)
#define MOVE_MOCKUP_PHYSICAL_MIASMA   (MOVE_END_OFFICIAL + 41)
#define MOVE_MOCKUP_PHYSICAL_EARTH    (MOVE_END_OFFICIAL + 42)
#define MOVE_MOCKUP_PHYSICAL_BEAST    (MOVE_END_OFFICIAL + 43)
#define MOVE_MOCKUP_PHYSICAL_HEART    (MOVE_END_OFFICIAL + 44)
#define MOVE_MOCKUP_PHYSICAL_NETHER   (MOVE_END_OFFICIAL + 45)
#define MOVE_MOCKUP_PHYSICAL_METAL    (MOVE_END_OFFICIAL + 46)
#define MOVE_MOCKUP_PHYSICAL_MYSTERY  (MOVE_END_OFFICIAL + 47)
#define MOVE_MOCKUP_PHYSICAL_FIRE     (MOVE_END_OFFICIAL + 48)
#define MOVE_MOCKUP_PHYSICAL_WATER    (MOVE_END_OFFICIAL + 49)
#define MOVE_MOCKUP_PHYSICAL_NATURE   (MOVE_END_OFFICIAL + 50)
#define MOVE_MOCKUP_PHYSICAL_WIND     (MOVE_END_OFFICIAL + 51)
#define MOVE_MOCKUP_PHYSICAL_REASON   (MOVE_END_OFFICIAL + 52)
#define MOVE_MOCKUP_PHYSICAL_ICE      (MOVE_END_OFFICIAL + 53)
#define MOVE_MOCKUP_PHYSICAL_DIVINE   (MOVE_END_OFFICIAL + 54)
#define MOVE_MOCKUP_PHYSICAL_DARK     (MOVE_END_OFFICIAL + 55)
#define MOVE_MOCKUP_PHYSICAL_ELECTRIC (MOVE_END_OFFICIAL + 56)
#define MOVE_MOCKUP_PHYSICAL_STELLAR  (MOVE_END_OFFICIAL + 57)
#define MOVE_MOCKUP_SPECIAL_ILLUSION  (MOVE_END_OFFICIAL + 58)
#define MOVE_MOCKUP_SPECIAL_DREAM     (MOVE_END_OFFICIAL + 59)
#define MOVE_MOCKUP_SPECIAL_FLYING    (MOVE_END_OFFICIAL + 60)
#define MOVE_MOCKUP_SPECIAL_MIASMA    (MOVE_END_OFFICIAL + 61)
#define MOVE_MOCKUP_SPECIAL_EARTH     (MOVE_END_OFFICIAL + 62)
#define MOVE_MOCKUP_SPECIAL_BEAST     (MOVE_END_OFFICIAL + 63)
#define MOVE_MOCKUP_SPECIAL_HEART     (MOVE_END_OFFICIAL + 64)
#define MOVE_MOCKUP_SPECIAL_NETHER    (MOVE_END_OFFICIAL + 65)
#define MOVE_MOCKUP_SPECIAL_METAL     (MOVE_END_OFFICIAL + 66)
#define MOVE_MOCKUP_SPECIAL_MYSTERY   (MOVE_END_OFFICIAL + 67)
#define MOVE_MOCKUP_SPECIAL_FIRE      (MOVE_END_OFFICIAL + 68)
#define MOVE_MOCKUP_SPECIAL_WATER     (MOVE_END_OFFICIAL + 69)
#define MOVE_MOCKUP_SPECIAL_NATURE    (MOVE_END_OFFICIAL + 70)
#define MOVE_MOCKUP_SPECIAL_WIND      (MOVE_END_OFFICIAL + 71)
#define MOVE_MOCKUP_SPECIAL_REASON    (MOVE_END_OFFICIAL + 72)
#define MOVE_MOCKUP_SPECIAL_ICE       (MOVE_END_OFFICIAL + 73)
#define MOVE_MOCKUP_SPECIAL_DIVINE    (MOVE_END_OFFICIAL + 74)
#define MOVE_MOCKUP_SPECIAL_DARK      (MOVE_END_OFFICIAL + 75)
#define MOVE_MOCKUP_SPECIAL_ELECTRIC  (MOVE_END_OFFICIAL + 76)
#define MOVE_MOCKUP_SPECIAL_STELLAR   (MOVE_END_OFFICIAL + 77)
#define MOVE_BEAT_UP_CALLING          (MOVE_END_OFFICIAL + 78)
#define MOVE_TAX_COLLECTION           (MOVE_END_OFFICIAL + 79)
#define MOVE_SCREEN_DIVIDE            (MOVE_END_OFFICIAL + 80)
#define MOVE_CROSS_DIVIDE             (MOVE_END_OFFICIAL + 81)

#define MOVE_BABY_FLAME               (MOVE_END_OFFICIAL + 82) // Agumon
#define MOVE_MEGA_FLAME               (MOVE_END_OFFICIAL + 83) // Greymon
#define MOVE_GIGA_DESTROYER           (MOVE_END_OFFICIAL + 84) // MetalGreymon
#define MOVE_GROUND_ZERO              (MOVE_END_OFFICIAL + 85) // SkullGreymon
#define MOVE_GREAT_TORNADO            (MOVE_END_OFFICIAL + 86) // WarGreymon
#define MOVE_MUGEN_CANNON             (MOVE_END_OFFICIAL + 87) // Mugendramon
#define MOVE_PETIT_FIRE               (MOVE_END_OFFICIAL + 88) // Gabumon
#define MOVE_FOX_FIRE                 (MOVE_END_OFFICIAL + 89) // Garurumon
#define MOVE_KAISER_NAIL              (MOVE_END_OFFICIAL + 90) // WereGarurumon
#define MOVE_COCYTUS_BREATH           (MOVE_END_OFFICIAL + 91) // MetalGarurumon
#define MOVE_GRACE_CROSS_FREEZER      (MOVE_END_OFFICIAL + 92) // MetalGarurumon
#define MOVE_GREY_SWORD               (MOVE_END_OFFICIAL + 93) // Omegamon
#define MOVE_GARURU_CANNON            (MOVE_END_OFFICIAL + 94) // Omegamon
#define MOVE_DOUBLE_TORRENT           (MOVE_END_OFFICIAL + 95) // Omegamon
#define MOVE_PETIT_THUNDER            (MOVE_END_OFFICIAL + 96) // Tentomon
#define MOVE_MEGA_BLASTER             (MOVE_END_OFFICIAL + 97) // Kabuterimon
#define MOVE_HORN_BUSTER              (MOVE_END_OFFICIAL + 98) // AtlurKabuterimon
#define MOVE_GIGA_SCISSOR_CLAW        (MOVE_END_OFFICIAL + 99) // HerculesKabuterimon
#define MOVE_POISON_IVY               (MOVE_END_OFFICIAL + 100) // Palmon
#define MOVE_PRICKLY_BANG_BANG        (MOVE_END_OFFICIAL + 101) // Togemon
#define MOVE_FLOWER_CANNON            (MOVE_END_OFFICIAL + 102) // Lilimon
#define MOVE_ROSES_RAPIER             (MOVE_END_OFFICIAL + 103) // Rosemon
#define MOVE_FORBIDDEN_TEMPTATION     (MOVE_END_OFFICIAL + 104) // Rosemon
#define MOVE_TURBO_PECKER             (MOVE_END_OFFICIAL + 105) // Piyomon
#define MOVE_METEOR_WING              (MOVE_END_OFFICIAL + 106) // Birdramon
#define MOVE_SHADOW_WING              (MOVE_END_OFFICIAL + 107) // Garudamon
#define MOVE_STARLIGHT_EXPLOSION      (MOVE_END_OFFICIAL + 108) // Hououmon
#define MOVE_CRIMSON_FLARE            (MOVE_END_OFFICIAL + 109) // Hououmon
/*
#define MOVE_MARCHING_FISHES          (MOVE_END_OFFICIAL + 110) // Gomamon
#define MOVE_HARPOON_VULCAN           (MOVE_END_OFFICIAL + 111) // Ikkakumon
#define MOVE_HAMMER_SPARK             (MOVE_END_OFFICIAL + 112) // Zudomon
#define MOVE_VIKING_FLARE             (MOVE_END_OFFICIAL + 113) // Vikemon
#define MOVE_MJOLLNIR_HAMMER          (MOVE_END_OFFICIAL + 114) // Vikemon
#define MOVE_AIR_SHOT                 (MOVE_END_OFFICIAL + 115) // Patamon
#define MOVE_SHOOTING_STAR            (MOVE_END_OFFICIAL + 116) // Pegasmon
#define MOVE_HEAVENS_KNUCKLE          (MOVE_END_OFFICIAL + 117) // Angemon
#define MOVE_HEAVENS_GATE             (MOVE_END_OFFICIAL + 118) // HolyAngemon
#define MOVE_EXCALIBUR                (MOVE_END_OFFICIAL + 119) // HolyAngemon
#define MOVE_SEVEN_HEAVENS            (MOVE_END_OFFICIAL + 120) // Seraphimon
#define MOVE_ASCENSION_HALLOW         (MOVE_END_OFFICIAL + 121) // Seraphimon
#define MOVE_PUPPY_HOWLING            (MOVE_END_OFFICIAL + 122) // Plotmon
#define MOVE_ROSETTA_STONE            (MOVE_END_OFFICIAL + 123) // Nefertimon
#define MOVE_NEKO_PUNCH               (MOVE_END_OFFICIAL + 124) // Tailmon
#define MOVE_HOLY_ARROW               (MOVE_END_OFFICIAL + 125) // Angewomon
#define MOVE_HEAVENS_CHARM            (MOVE_END_OFFICIAL + 126) // Angewomon
#define MOVE_EDENS_JAVELIN            (MOVE_END_OFFICIAL + 127) // Ophanimon
#define MOVE_APOCALYPSE               (MOVE_END_OFFICIAL + 128) // Ophanimon
#define MOVE_VEEMON_HEAD              (MOVE_END_OFFICIAL + 129) // V-mon
#define MOVE_KNUCKLE_FIRE             (MOVE_END_OFFICIAL + 130) // Fladramon
#define MOVE_LIGHTNING_BLADE          (MOVE_END_OFFICIAL + 131) // Lightdramon
#define MOVE_PLASMA_SHOOT             (MOVE_END_OFFICIAL + 132) // Magnamon
#define MOVE_EXTREME_JIHAD            (MOVE_END_OFFICIAL + 133) // Magnamon
#define MOVE_X_LASER                  (MOVE_END_OFFICIAL + 134) // XV-mon
#define MOVE_DESPERADO_BLASTER        (MOVE_END_OFFICIAL + 135) // Paildramon
#define MOVE_MEGA_DEATH               (MOVE_END_OFFICIAL + 136) // Imperialdramon
#define MOVE_SPLENDOR_BLADE           (MOVE_END_OFFICIAL + 137) // Imperialdramon
#define MOVE_GIGA_DEATH               (MOVE_END_OFFICIAL + 138) // Imperialdramon
#define MOVE_POSITRON_LASER           (MOVE_END_OFFICIAL + 139) // Imperialdramon
#define MOVE_OMEGA_BLADE              (MOVE_END_OFFICIAL + 140) // Imperialdramon
#define MOVE_STIKY_NET                (MOVE_END_OFFICIAL + 141) // Wormmon
#define MOVE_SPIKING_FINISH           (MOVE_END_OFFICIAL + 142) // Stingmon
#define MOVE_ROLLING_STONE            (MOVE_END_OFFICIAL + 143) // Armadimon
#define MOVE_GOLD_RUSH                (MOVE_END_OFFICIAL + 144) // Digmon
#define MOVE_OXYGEN_HOMING            (MOVE_END_OFFICIAL + 145) // Submarimon
#define MOVE_TAIL_HAMMER              (MOVE_END_OFFICIAL + 146) // Ankylomon
#define MOVE_ARAMITAMA                (MOVE_END_OFFICIAL + 147) // Shakkoumon
#define MOVE_FEATHER_SLASH            (MOVE_END_OFFICIAL + 148) // Hawkmon
#define MOVE_MACH_IMPULSE             (MOVE_END_OFFICIAL + 149) // Holsemon
#define MOVE_KUSANAGI                 (MOVE_END_OFFICIAL + 150) // Shurimon
#define MOVE_GLIDE_HORN               (MOVE_END_OFFICIAL + 151) // Aquilamon
#define MOVE_TOP_GUN                  (MOVE_END_OFFICIAL + 152) // Silphymon
#define MOVE_FENRIR_SWORD             (MOVE_END_OFFICIAL + 153) // Valkyrimon
#define MOVE_AURVANDILS_ARROW         (MOVE_END_OFFICIAL + 154) // Valkyrimon
#define MOVE_PICO_DART                (MOVE_END_OFFICIAL + 155) // PicoDevimon
#define MOVE_DEATH_CLAW               (MOVE_END_OFFICIAL + 156) // Devimon
#define MOVE_NIGHT_RAID               (MOVE_END_OFFICIAL + 157) // Vamdemon
#define MOVE_VENOM_INFUSION           (MOVE_END_OFFICIAL + 158) // VenomVamdemon
#define MOVE_PANDEMONIUM_FLAME        (MOVE_END_OFFICIAL + 159) // BelialVamdemon
#define MOVE_DARKNESS_WAVE            (MOVE_END_OFFICIAL + 160) // LadyDevimon
#define MOVE_PHANTOM_PAIN             (MOVE_END_OFFICIAL + 161) // Lilithmon
#define MOVE_DARKNESS_LOVE            (MOVE_END_OFFICIAL + 162) // Lilithmon
#define MOVE_ELECTRIC_SHOCK           (MOVE_END_OFFICIAL + 163) // Betamon
#define MOVE_ICE_ARROW                (MOVE_END_OFFICIAL + 164) // Seadramon
#define MOVE_THUNDER_JAVELIN          (MOVE_END_OFFICIAL + 165) // MegaSeadramon
#define MOVE_ULTIMATE_STREAM          (MOVE_END_OFFICIAL + 166) // MetalSeadramon
#define MOVE_CABLE_CRUSHER            (MOVE_END_OFFICIAL + 167) // Diablomon
#define MOVE_WEB_WRECKER              (MOVE_END_OFFICIAL + 168) // Diablomon
#define MOVE_LOST_PARADISE            (MOVE_END_OFFICIAL + 169) // Diablomon
*/

#define MOVE_ADDED_MODERN_END       MOVE_CRIMSON_FLARE

#define MOVE_MIKO_CHARITY           (MOVE_ADDED_MODERN_END + 1)
#define MOVE_SILENCING              (MOVE_ADDED_MODERN_END + 2)
#define MOVE_KILLER_DOLL            (MOVE_ADDED_MODERN_END + 3)
#define MOVE_SEAL_NEEDLE            (MOVE_ADDED_MODERN_END + 4)
#define MOVE_HOMING_NEEDLE          (MOVE_ADDED_MODERN_END + 5)
#define MOVE_PRIVATE_SQUARE         (MOVE_ADDED_MODERN_END + 6)
#define MOVE_FEATHER_JAB            (MOVE_ADDED_MODERN_END + 7)
#define MOVE_DRAGON_DRILL           (MOVE_ADDED_MODERN_END + 8)
#define MOVE_TENSION_KICK           (MOVE_ADDED_MODERN_END + 9)
#define MOVE_SAKURA_STORM           (MOVE_ADDED_MODERN_END + 10)
#define MOVE_DOLL_STRINGS           (MOVE_ADDED_MODERN_END + 11)
#define MOVE_DRAGON_METEOR          (MOVE_ADDED_MODERN_END + 12)
#define MOVE_HISOU_SWORD            (MOVE_ADDED_MODERN_END + 13)
#define MOVE_ENVY                   (MOVE_ADDED_MODERN_END + 14)
#define MOVE_ISOLATION              (MOVE_ADDED_MODERN_END + 15)
#define MOVE_BLACK_WIND             (MOVE_ADDED_MODERN_END + 16)
#define MOVE_ARTFUL_SACRIFICE       (MOVE_ADDED_MODERN_END + 17)
#define MOVE_PAIN_FLOW              (MOVE_ADDED_MODERN_END + 18)
#define MOVE_MALLET_SMASH           (MOVE_ADDED_MODERN_END + 19)
#define MOVE_LITTLE_LEGION          (MOVE_ADDED_MODERN_END + 20)
#define MOVE_PERSUASION_NEEDLE      (MOVE_ADDED_MODERN_END + 21)
#define MOVE_ONI_BINDING            (MOVE_ADDED_MODERN_END + 22)
#define MOVE_LUNA_DIAL              (MOVE_ADDED_MODERN_END + 23)
#define MOVE_WRIGGLE_KICK           (MOVE_ADDED_MODERN_END + 24)
#define MOVE_LUNATIC_RED_EYES       (MOVE_ADDED_MODERN_END + 25)
#define MOVE_POISON_BREATH          (MOVE_ADDED_MODERN_END + 26)
#define MOVE_FOCUS_FLIGHT           (MOVE_ADDED_MODERN_END + 27)
#define MOVE_PIPICE                 (MOVE_ADDED_MODERN_END + 28)
#define MOVE_TRAIN_WRECK            (MOVE_ADDED_MODERN_END + 29)
#define MOVE_LIFE_COUNTER           (MOVE_ADDED_MODERN_END + 30)
#define MOVE_MINDS_EYE              (MOVE_ADDED_MODERN_END + 31)
#define MOVE_VOODOO_DOLL            (MOVE_ADDED_MODERN_END + 32)
#define MOVE_UNEXPLAINED_FEVER      (MOVE_ADDED_MODERN_END + 33)
#define MOVE_OCCULT_DANCE           (MOVE_ADDED_MODERN_END + 34)
#define MOVE_INVISIBLE_FULLMOON     (MOVE_ADDED_MODERN_END + 35)
#define MOVE_SPARROW_SONG           (MOVE_ADDED_MODERN_END + 36)
#define MOVE_SMASHY_SMASH           (MOVE_ADDED_MODERN_END + 37)
#define MOVE_TREMORS                (MOVE_ADDED_MODERN_END + 38)
#define MOVE_SUNNY_MILK             (MOVE_ADDED_MODERN_END + 39)
#define MOVE_SUPER_EGO              (MOVE_ADDED_MODERN_END + 40)
#define MOVE_PRISM_LIVE             (MOVE_ADDED_MODERN_END + 41)
#define MOVE_HELLS_TOKAMAK          (MOVE_ADDED_MODERN_END + 42)
#define MOVE_EX_ONBASHIRA           (MOVE_ADDED_MODERN_END + 43)
#define MOVE_LAEVATEIN              (MOVE_ADDED_MODERN_END + 44)
#define MOVE_SPINNING               (MOVE_ADDED_MODERN_END + 45)

#define MOVE_CLASSIC_FLAMETHROWER   (MOVE_ADDED_MODERN_END + 46)
#define MOVE_CLASSIC_MASTER_SPARK   (MOVE_ADDED_MODERN_END + 47)
#define MOVE_CLASSIC_THUNDERBOLT    (MOVE_ADDED_MODERN_END + 48)
#define MOVE_CLASSIC_AMNESIA        (MOVE_ADDED_MODERN_END + 49)

#define MOVE_CARD_INCLUDE                        (MOVE_ADDED_MODERN_END + 50)
#define MOVE_CARD_INCLUDE_BELLEROPHON            (MOVE_ADDED_MODERN_END + 51) // Wind Physical
#define MOVE_CARD_INCLUDE_EXCALIBUR_SPECIAL      (MOVE_ADDED_MODERN_END + 52) // Wind Special
#define MOVE_CARD_INCLUDE_BUDDHA_PALM            (MOVE_ADDED_MODERN_END + 53) // Divine Physical
#define MOVE_CARD_INCLUDE_ENUMA_ELISH            (MOVE_ADDED_MODERN_END + 54) // Divine Special
#define MOVE_CARD_INCLUDE_UNLIMITED_BLADE_WORKS  (MOVE_ADDED_MODERN_END + 55) // Reason Physical
#define MOVE_CARD_INCLUDE_SANAT_KUMARA           (MOVE_ADDED_MODERN_END + 56) // Reason Special
#define MOVE_CARD_INCLUDE_GAE_BOLG               (MOVE_ADDED_MODERN_END + 57) // Steel Physical
#define MOVE_CARD_INCLUDE_HOLLOW_HEART_ALBION    (MOVE_ADDED_MODERN_END + 58) // Steel Special
#define MOVE_CARD_INCLUDE_GANRYU_JIMA            (MOVE_ADDED_MODERN_END + 59) // Water Physical
#define MOVE_CARD_INCLUDE_SECECE_MORGAN          (MOVE_ADDED_MODERN_END + 60) // Water Special
#define MOVE_CARD_INCLUDE_ZABANIYA               (MOVE_ADDED_MODERN_END + 61) // Miasma Physical
#define MOVE_CARD_INCLUDE_ANGRA_MANYU_CURSE      (MOVE_ADDED_MODERN_END + 62) // Miasma Special
#define MOVE_CARD_INCLUDE_CHARIOT_MY_LOVE        (MOVE_ADDED_MODERN_END + 63) // Heart Physical
#define MOVE_CARD_INCLUDE_SAMSARA_KAMA           (MOVE_ADDED_MODERN_END + 64) // Heart Special
#define MOVE_CARD_INCLUDE_NINE_LIVES_BLADES_WORK (MOVE_ADDED_MODERN_END + 65) // Beast Physical
#define MOVE_CARD_INCLUDE_SAMADHI_FLAMES         (MOVE_ADDED_MODERN_END + 66) // Beast Special
#define MOVE_CARD_INCLUDE_TARASQUE               (MOVE_ADDED_MODERN_END + 67) // Dream Physical 
#define MOVE_CARD_INCLUDE_UOMO_UNIVERSALE        (MOVE_ADDED_MODERN_END + 68) // Dream Special
#define MOVE_CARD_INCLUDE_OPUTATESHIKE_OKIMUNPE  (MOVE_ADDED_MODERN_END + 69) // Ice Phycial
#define MOVE_CARD_INCLUDE_VIY_VIY_VIY            (MOVE_ADDED_MODERN_END + 70) // Ice Special
#define MOVE_CARD_INCLUDE_RASHOUMON_DAIENGI      (MOVE_ADDED_MODERN_END + 71) // Fire Physical
#define MOVE_CARD_INCLUDE_EXCALIBUR_GALATINE     (MOVE_ADDED_MODERN_END + 72) // Fire Special
#define MOVE_CARD_INCLUDE_RULE_BREAKER           (MOVE_ADDED_MODERN_END + 73) // Nether Physical
#define MOVE_CARD_INCLUDE_KUR_KI_GAL_IRKALA      (MOVE_ADDED_MODERN_END + 74) // Nether Special
#define MOVE_CARD_INCLUDE_HIPPOGRIF              (MOVE_ADDED_MODERN_END + 75) // Flying Physical
#define MOVE_CARD_INCLUDE_VALKYRIE_RAGNAROG      (MOVE_ADDED_MODERN_END + 76) // Flying Special
#define MOVE_CARD_INCLUDE_NEZUMI_JOUDO           (MOVE_ADDED_MODERN_END + 77) // Earth Physical
#define MOVE_CARD_INCLUDE_EARTHLIGHT_STARBOW     (MOVE_ADDED_MODERN_END + 78) // Earth Special
#define MOVE_CARD_INCLUDE_BLASTED_TREE           (MOVE_ADDED_MODERN_END + 79) // Electric Physical
#define MOVE_CARD_INCLUDE_SYSTEM_KERAUNOS        (MOVE_ADDED_MODERN_END + 80) // Electric Special
#define MOVE_CARD_INCLUDE_HAMISH_AVALIM          (MOVE_ADDED_MODERN_END + 81) // Nature Physical
#define MOVE_CARD_INCLUDE_KAMA_RUPASTRA          (MOVE_ADDED_MODERN_END + 82) // Nature Special
#define MOVE_CARD_INCLUDE_MARIA_THE_RIPPER       (MOVE_ADDED_MODERN_END + 83) // Dark Special
#define MOVE_CARD_INCLUDE_ISHA_RAA               (MOVE_ADDED_MODERN_END + 84) // Dark Special
#define MOVE_CARD_INCLUDE_MARBLE_PHANTASM        (MOVE_ADDED_MODERN_END + 85) // Illusion Physical
#define MOVE_CARD_INCLUDE_RAYPROOF_KYRIELIGHT    (MOVE_ADDED_MODERN_END + 86) // Illusion Special

#define MOVE_END_CLASSIC            MOVE_CARD_INCLUDE_RAYPROOF_KYRIELIGHT

#define MOVE_EX_SHADOW_BLITZ        (MOVE_END_CLASSIC + 1)
#define MOVE_EX_SHADOW_RUSH         (MOVE_END_CLASSIC + 2)
#define MOVE_EX_SHADOW_BREAK        (MOVE_END_CLASSIC + 3)
#define MOVE_EX_SHADOW_END          (MOVE_END_CLASSIC + 4)
#define MOVE_EX_SHADOW_WAVE         (MOVE_END_CLASSIC + 5)
#define MOVE_EX_SHADOW_RAVE         (MOVE_END_CLASSIC + 6)
#define MOVE_EX_SHADOW_STORM        (MOVE_END_CLASSIC + 7)
#define MOVE_EX_SHADOW_FIRE         (MOVE_END_CLASSIC + 8)
#define MOVE_EX_SHADOW_BOLT         (MOVE_END_CLASSIC + 9)
#define MOVE_EX_SHADOW_CHILL        (MOVE_END_CLASSIC + 10)
#define MOVE_EX_SHADOW_BLAST        (MOVE_END_CLASSIC + 11)
#define MOVE_EX_SHADOW_SKY          (MOVE_END_CLASSIC + 12)
#define MOVE_EX_SHADOW_HOLD         (MOVE_END_CLASSIC + 13)
#define MOVE_EX_SHADOW_MIST         (MOVE_END_CLASSIC + 14)
#define MOVE_EX_SHADOW_PANIC        (MOVE_END_CLASSIC + 15)
#define MOVE_EX_SHADOW_DOWN         (MOVE_END_CLASSIC + 16)
#define MOVE_EX_SHADOW_SHED         (MOVE_END_CLASSIC + 17)
#define MOVE_EX_SHADOW_HALF         (MOVE_END_CLASSIC + 18)

#define MOVE_END_EX_SHADOW_MOVES       MOVE_EX_SHADOW_HALF

#define MOVE_END_ADDED      MOVE_END_EX_SHADOW_MOVES

#define MOVES_COUNT_GEN9    (MOVE_END_ADDED + 1)

#define MOVES_COUNT         MOVES_COUNT_GEN9

// Z Moves
#define MOVE_BREAKNECK_BLITZ (MOVES_COUNT + 0)
#define MOVE_ALL_OUT_PUMMELING (MOVES_COUNT + 1)
#define MOVE_SUPERSONIC_SKYSTRIKE (MOVES_COUNT + 2)
#define MOVE_ACID_DOWNPOUR (MOVES_COUNT + 3)
#define MOVE_TECTONIC_RAGE (MOVES_COUNT + 4)
#define MOVE_CONTINENTAL_CRUSH (MOVES_COUNT + 5)
#define MOVE_SAVAGE_SPIN_OUT (MOVES_COUNT + 6)
#define MOVE_NEVER_ENDING_NIGHTMARE (MOVES_COUNT + 7)
#define MOVE_CORKSCREW_CRASH (MOVES_COUNT + 8)
#define MOVE_INFERNO_OVERDRIVE (MOVES_COUNT + 9)
#define MOVE_HYDRO_VORTEX (MOVES_COUNT + 10)
#define MOVE_BLOOM_DOOM (MOVES_COUNT + 11)
#define MOVE_GIGAVOLT_HAVOC (MOVES_COUNT + 12)
#define MOVE_SHATTERED_PSYCHE (MOVES_COUNT + 13)
#define MOVE_SUBZERO_SLAMMER (MOVES_COUNT + 14)
#define MOVE_DEVASTATING_DRAKE (MOVES_COUNT + 15)
#define MOVE_BLACK_HOLE_ECLIPSE (MOVES_COUNT + 16)
#define MOVE_TWINKLE_TACKLE (MOVES_COUNT + 17)

// Signature Z Moves
#define MOVE_CATASTROPIKA (MOVES_COUNT + 18)
#define MOVE_10000000_VOLT_THUNDERBOLT (MOVES_COUNT + 19)
#define MOVE_10_000_000_VOLT_THUNDERBOLT MOVE_10000000_VOLT_THUNDERBOLT
#define MOVE_STOKED_SPARKSURFER (MOVES_COUNT + 20)
#define MOVE_EXTREME_EVOBOOST (MOVES_COUNT + 21)
#define MOVE_PULVERIZING_PANCAKE (MOVES_COUNT + 22)
#define MOVE_GENESIS_SUPERNOVA (MOVES_COUNT + 23)
#define MOVE_SINISTER_ARROW_RAID (MOVES_COUNT + 24)
#define MOVE_MALICIOUS_MOONSAULT (MOVES_COUNT + 25)
#define MOVE_OCEANIC_OPERETTA (MOVES_COUNT + 26)
#define MOVE_SPLINTERED_STORMSHARDS (MOVES_COUNT + 27)
#define MOVE_LETS_SNUGGLE_FOREVER (MOVES_COUNT + 28)
#define MOVE_CLANGOROUS_SOULBLAZE (MOVES_COUNT + 29)
#define MOVE_GUARDIAN_OF_ALOLA (MOVES_COUNT + 30)
#define MOVE_SEARING_SUNRAZE_SMASH (MOVES_COUNT + 31)
#define MOVE_NEW_SABOTEN_BREAKOUT_COMPLETE_SMASH MOVE_SEARING_SUNRAZE_SMASH // TNDYS
#define MOVE_MENACING_MOONRAZE_MAELSTROM (MOVES_COUNT + 32)
#define MOVE_LIGHT_THAT_BURNS_THE_SKY (MOVES_COUNT + 33)
#define MOVE_NEW_THERE_IS_NO_FANTASY_HEAVEN MOVE_LIGHT_THAT_BURNS_THE_SKY // TNDYS
#define MOVE_SOUL_STEALING_7_STAR_STRIKE (MOVES_COUNT + 34)

#define FIRST_Z_MOVE        MOVE_BREAKNECK_BLITZ
#define LAST_Z_MOVE         MOVE_SOUL_STEALING_7_STAR_STRIKE

#define MOVES_COUNT_Z       (LAST_Z_MOVE + 1)

//Max Moves
#define MOVE_MAX_GUARD          (FIRST_MAX_MOVE + 0)
#define MOVE_MAX_STRIKE         (FIRST_MAX_MOVE + 1)
#define MOVE_MAX_KNUCKLE        (FIRST_MAX_MOVE + 2)
#define MOVE_MAX_AIRSTREAM      (FIRST_MAX_MOVE + 3)
#define MOVE_MAX_OOZE           (FIRST_MAX_MOVE + 4)
#define MOVE_MAX_QUAKE          (FIRST_MAX_MOVE + 5)
#define MOVE_MAX_ROCKFALL       (FIRST_MAX_MOVE + 6)
#define MOVE_MAX_FLUTTERBY      (FIRST_MAX_MOVE + 7)
#define MOVE_MAX_PHANTASM       (FIRST_MAX_MOVE + 8)
#define MOVE_MAX_STEELSPIKE     (FIRST_MAX_MOVE + 9)
#define MOVE_MAX_FLARE          (FIRST_MAX_MOVE + 10)
#define MOVE_MAX_GEYSER         (FIRST_MAX_MOVE + 11)
#define MOVE_MAX_OVERGROWTH     (FIRST_MAX_MOVE + 12)
#define MOVE_MAX_LIGHTNING      (FIRST_MAX_MOVE + 13)
#define MOVE_MAX_MINDSTORM      (FIRST_MAX_MOVE + 14)
#define MOVE_MAX_HAILSTORM      (FIRST_MAX_MOVE + 15)
#define MOVE_MAX_WYRMWIND       (FIRST_MAX_MOVE + 16)
#define MOVE_MAX_DARKNESS       (FIRST_MAX_MOVE + 17)
#define MOVE_MAX_STARFALL       (FIRST_MAX_MOVE + 18)
// Gigantamax Moves
#define MOVE_G_MAX_VINE_LASH    (FIRST_MAX_MOVE + 19)
#define MOVE_G_MAX_WILDFIRE     (FIRST_MAX_MOVE + 20)
#define MOVE_G_MAX_CANNONADE    (FIRST_MAX_MOVE + 21)
#define MOVE_G_MAX_BEFUDDLE     (FIRST_MAX_MOVE + 22)
#define MOVE_G_MAX_VOLT_CRASH   (FIRST_MAX_MOVE + 23)
#define MOVE_G_MAX_GOLD_RUSH    (FIRST_MAX_MOVE + 24)
#define MOVE_G_MAX_CHI_STRIKE   (FIRST_MAX_MOVE + 25)
#define MOVE_G_MAX_TERROR       (FIRST_MAX_MOVE + 26)
#define MOVE_G_MAX_FOAM_BURST   (FIRST_MAX_MOVE + 27)
#define MOVE_G_MAX_RESONANCE    (FIRST_MAX_MOVE + 28)
#define MOVE_G_MAX_CUDDLE       (FIRST_MAX_MOVE + 29)
#define MOVE_G_MAX_REPLENISH    (FIRST_MAX_MOVE + 30)
#define MOVE_G_MAX_MALODOR      (FIRST_MAX_MOVE + 31)
#define MOVE_G_MAX_MELTDOWN     (FIRST_MAX_MOVE + 32)
#define MOVE_G_MAX_DRUM_SOLO    (FIRST_MAX_MOVE + 33)
#define MOVE_G_MAX_FIREBALL     (FIRST_MAX_MOVE + 34)
#define MOVE_G_MAX_HYDROSNIPE   (FIRST_MAX_MOVE + 35)
#define MOVE_G_MAX_WIND_RAGE    (FIRST_MAX_MOVE + 36)
#define MOVE_G_MAX_GRAVITAS     (FIRST_MAX_MOVE + 37)
#define MOVE_G_MAX_STONESURGE   (FIRST_MAX_MOVE + 38)
#define MOVE_G_MAX_VOLCALITH    (FIRST_MAX_MOVE + 39)
#define MOVE_G_MAX_TARTNESS     (FIRST_MAX_MOVE + 40)
#define MOVE_G_MAX_SWEETNESS    (FIRST_MAX_MOVE + 41)
#define MOVE_G_MAX_SANDBLAST    (FIRST_MAX_MOVE + 42)
#define MOVE_G_MAX_STUN_SHOCK   (FIRST_MAX_MOVE + 43)
#define MOVE_G_MAX_CENTIFERNO   (FIRST_MAX_MOVE + 44)
#define MOVE_G_MAX_SMITE        (FIRST_MAX_MOVE + 45)
#define MOVE_G_MAX_SNOOZE       (FIRST_MAX_MOVE + 46)
#define MOVE_G_MAX_FINALE       (FIRST_MAX_MOVE + 47)
#define MOVE_G_MAX_STEELSURGE   (FIRST_MAX_MOVE + 48)
#define MOVE_G_MAX_DEPLETION    (FIRST_MAX_MOVE + 49)
#define MOVE_G_MAX_ONE_BLOW     (FIRST_MAX_MOVE + 50)
#define MOVE_G_MAX_RAPID_FLOW   (FIRST_MAX_MOVE + 51)

#define FIRST_MAX_MOVE        MOVES_COUNT_Z
#define LAST_MAX_MOVE         MOVE_G_MAX_RAPID_FLOW

#define MOVES_COUNT_DYNAMAX       (LAST_MAX_MOVE + 1)

#define MOVES_COUNT_ALL         MOVES_COUNT_DYNAMAX

// Used for checks for moves affected by Disable, Mimic, etc.
#define MOVE_UNAVAILABLE 0xFFFF

#endif  // GUARD_CONSTANTS_MOVES_H
