Route6_Frlg_MapScripts::
	.byte 0

Route6_EventScript_UndergroundPathSign::
	msgbox Route6_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route6_Text_RickyIntro::
	.string "Who's there?\n"
	.string "Quit listening in on us!$"

Route6_Text_RickyDefeat::
	.string "I just can't win!$"

Route6_Text_RickyPostBattle::
	.string "Whisper…\n"
	.string "Whisper…$"

Route6_Text_NancyIntro::
	.string "Excuse me!\n"
	.string "This is a private conversation!$"

Route6_Text_NancyDefeat::
	.string "Ugh!\n"
	.string "I hate losing.$"

Route6_Text_NancyPostBattle::
	.string "Whisper…\n"
	.string "Whisper…$"

Route6_Text_KeigoIntro::
	.string "There aren't many bugs out here.$"

Route6_Text_KeigoDefeat::
	.string "No!\n"
	.string "You're kidding!$"

Route6_Text_KeigoPostBattle::
	.string "I like bugs, so I'm going back to\n"
	.string "VIRIDIAN FOREST.$"

Route6_Text_JeffIntro::
	.string "Huh?\n"
	.string "You want to talk to me?$"

Route6_Text_JeffDefeat::
	.string "This stinks…\n"
	.string "I couldn't beat your challenge…$"

Route6_Text_JeffPostBattle::
	.string "I should bring more POKéMON with\n"
	.string "me. I'll feel safer that way.$"

Route6_Text_IsabelleIntro::
	.string "Me?\n"
	.string "Well, okay. I'll play!$"

Route6_Text_IsabelleDefeat::
	.string "Things just didn't work…$"

Route6_Text_IsabellePostBattle::
	.string "I want to get stronger.\n"
	.string "What's your secret?$"

Route6_Text_ElijahIntro::
	.string "I've never seen you around.\n"
	.string "Are you good?$"

Route6_Text_ElijahDefeat::
	.string "You're too good!$"

Route6_Text_ElijahPostBattle::
	.string "Are my POKéMON weak?\n"
	.string "Or, am I just bad?\l"
	.string "Which do you think?$"

Route6_Text_DayIntro::
	.string "DAY: Are you going to beat us?$" 
		
Route6_Text_DayDefeat::
	.string "DAY: Waah!$"

Route6_Text_DayPostBattle::
	.string "DAY: Looks like we got bounced.$"

Route6_Text_DayNotEnoughMons::
	.string "DAY: If you want to battle with\n"
	.string "us, you have to bring at least two\l"
	.string "POKéMON with you.$"

Route6_Text_DaniIntro::
	.string "DANI: We'll knock you flat!$"

Route6_Text_DaniDefeat::
	.string "DANI: Eeeh!$"

Route6_Text_DaniPostBattle::
	.string "DANI: You beat us…$"

Route6_Text_DaniNotEnoughMons::
	.string "DANI: If you want to battle with\n"
	.string "us, you have to bring at least two\l"
	.string "POKéMON with you.$"

Route6_Text_UndergroundPathSign::
	.string "UNDERGROUND PATH\n"
	.string "CERULEAN CITY - VERMILION CITY$"
