Route3_Frlg_MapScripts::
	.byte 0

Route3_EventScript_Youngster::
	msgbox Route3_Text_TunnelFromCeruleanTiring, MSGBOX_NPC
	end

Route3_EventScript_RouteSign::
	msgbox Route3_Text_RouteSign, MSGBOX_SIGN
	end

Route3_Text_TunnelFromCeruleanTiring::
	.string "Whew… I better take a rest…\n"
	.string "Groan…\p"
	.string "That tunnel from CERULEAN takes a\n"
	.string "lot out of you!$"

Route3_Text_ColtonIntro::
	.string "Hey!\n"
	.string "I saw you in VIRIDIAN FOREST!$"

Route3_Text_ColtonDefeat::
	.string "You beat me again!$"

Route3_Text_ColtonPostBattle::
	.string "There are other kinds of POKéMON\n"
	.string "than the ones you find in forests.$"

Route3_Text_BenIntro::
	.string "Hi!\n"
	.string "I like shorts!\p"
	.string "They're delightfully comfy and\n"
	.string "easy to wear!$"

Route3_Text_BenDefeat::
	.string "I don't believe it!$"

Route3_Text_BenPostBattle::
	.string "Are you using a POKéMON CENTER's\n"
	.string "PC for storing your POKéMON?\p"
	.string "Each BOX can hold up to\n"
	.string "30 POKéMON.$"

Route3_Text_JaniceIntro::
	.string "Excuse me!\n"
	.string "You looked at me, didn't you?$"

Route3_Text_JaniceDefeat::
	.string "You're mean!$"

Route3_Text_JanicePostBattle::
	.string "You shouldn't be staring if you\n"
	.string "don't want to battle!$"

Route3_Text_GregIntro::
	.string "Are you a TRAINER?\n"
	.string "Let's get with it right away!$"

Route3_Text_GregDefeat::
	.string "If I had new POKéMON, I would've\n"
	.string "won!$"

Route3_Text_GregPostBattle::
	.string "If a POKéMON BOX on the PC gets\n"
	.string "full, just switch to another BOX.$"

Route3_Text_SallyIntro::
	.string "That look you gave me…\n"
	.string "It's so intriguing!$"

Route3_Text_SallyDefeat::
	.string "Be nice!$"

Route3_Text_SallyPostBattle::
	.string "You can avoid battles by not\n"
	.string "letting TRAINERS see you.$"

Route3_Text_CalvinIntro::
	.string "Hey! You're not wearing shorts!\n"
	.string "What's wrong with you?$"

Route3_Text_CalvinDefeat::
	.string "Lost!\n"
	.string "Lost! Lost!$"

Route3_Text_CalvinPostBattle::
	.string "I always wear shorts, even in\n"
	.string "winter. That's my policy.$"

Route3_Text_JimmyIntro::
	.string "I can run like the wind!$"
	
Route3_Text_JimmyDefeat::
	.string "Blown away!$"

Route3_Text_JimmyPostBattle::
	.string "Time to run home!$"

Route3_Text_RobinIntro::
	.string "Eek!\n"
	.string "Did you touch me?$"

Route3_Text_RobinDefeat::
	.string "That's it?$"

Route3_Text_RobinPostBattle::
	.string "ROUTE 4 is at the foot of\n"
	.string "MT. MOON.$"

Route3_Text_RouteSign::
	.string "ROUTE 3\n"
	.string "MT. MOON AHEAD$"

Route3_Text_BruceIntro::
	.string "My bag is digging into my shoulders!\n"
	.string "When that happens, I like to take a\p"
	.string "break and have a battle!$"

Route3_Text_BruceDefeat::
	.string "Feh.$"

Route3_Text_BrucePostBattle::
	.string "All right, guess I should carry my\n"
	.string "bag again!$"

Route3_Text_DwightIntro::
	.string "Peace!\p"
	.string "…\n"
	.string "…Huh?\p"
	.string "When you meet the unknown on a\n"
	.string "mountain road, all you want is peace,\l"
	.string "right?$"

Route3_Text_DwightDefeat::
	.string "Peace--even though I lost!$"

Route3_Text_DwightPostBattle::
	.string "Exchanging lighthearted greetings with\n"
	.string "someone you don't know…\p"
	.string "That's the best thing about mountains!$"

Route3_Text_ZacIntro::
	.string "ZAC: Really, you want to battle us?\p"
	.string "You've got a lot of courage for someone\n"
	.string "so young.$"

Route3_Text_ZacDefeat::
	.string "ZAC: You weren't bluffing…$"

Route3_Text_ZacPostBattle::
	.string "ZAC: Your future looks promising.$"

Route3_Text_ZacNotEnoughMons::
	.string "ZAC: If you want to battle with\n"
	.string "us, you have to bring at least two\l"
	.string "POKéMON with you.$"

Route3_Text_JenIntro::
	.string "JEN: Huh? You'd like to go up against\n"
	.string "us? Great!$"

Route3_Text_JenDefeat::
	.string "JEN: You're so much stronger than\n"
	.string "I thought.$"

Route3_Text_JenPostBattle::
	.string "JEN: I'm looking forward to seeing what\n"
	.string "kind of Trainer you'll become.$"

Route3_Text_JenNotEnoughMons::
	.string "JEN: If you want to battle with\n"
	.string "us, you have to bring at least two\l"
	.string "POKéMON with you.$"
