Route25_Cape_Frlg_MapScripts::
	.byte 0

Route25_Text_KevinIntro::
	.string "After seeing how you battle, I want\n"
	.string	"to see how I'll fare.\p"
    .string "How about it? Let me take you on.$"

Route25_Text_KevinDefeat::
	.string "I've never had a battle this good!$"

Route25_Text_KevinPostBattle::
	.string "That was a great battle! You and\n" 
    .string "your POKEMON are truly outstanding!$"
